---
title: "CV10"
output: html_notebook
---

## tabella finale
CV10 <- rbind(U01CV10_check_total, U02CV10_check_total, U03CV10_check_total,
             U04CV10_check_total, U05CV10_check_total, U06CV10_check_total,
             U07CV10_check_total, U08CV10_check_total, U09CV10_check_total,
             U10CV10_check_total, U11CV10_check_total, U12CV10_check_total)

```{r}
library("jsonlite")
library("dplyr")
library("tidyr")
library("tidyverse")
library("data.table")
library("xlsx")
```

```{r}
## ------------------- U01CV10 -------------------
## copio dati da JSON
U01CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_03_14_02_05_U01.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU01CV10<-U01CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU01CV10<-U01CV10[[2]][[1]]
objectsPositionU01CV10$Utente <- "U01CV"

## creo tabella per ogni oggetto
Cube2U01CV10 <- objectsPositionU01CV10[objectsPositionU01CV10$objPosition %like% "Cube2", ]
Cube2U01CV10$Utente <- "U01CV"
## controllo ultima posizione
U01CV10_check_Cube2 <- tail(Cube2U01CV10, n = 1)

CapsuleU01CV10 <- objectsPositionU01CV10[objectsPositionU01CV10$objPosition %like% "Capsule", ]
CapsuleU01CV10$Utente <- "U01CV"
## controllo ultima posizione
U01CV10_check_Capsule <- tail(CapsuleU01CV10, n = 1)

Cube_1U01CV10 <- objectsPositionU01CV10[objectsPositionU01CV10$objPosition %like% "Cube 1", ]
Cube_1U01CV10$Utente <- "U01CV"
## controllo ultima posizione
U01CV10_check_Cube_1 <- tail(Cube_1U01CV10, n = 1)

CubeU01CV10 <- objectsPositionU01CV10[objectsPositionU01CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U01CV10_check_Cube <- tail(CubeU01CV10, n = 1)

CylinderU01CV10 <- objectsPositionU01CV10[objectsPositionU01CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U01CV10_check_Cylinder <- tail(CylinderU01CV10, n = 1)

EggU01CV10 <- objectsPositionU01CV10[objectsPositionU01CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U01CV10_check_Egg <- tail(EggU01CV10, n = 1)

Capsule2U01CV10 <- objectsPositionU01CV10[objectsPositionU01CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U01CV10_check_Capsule2 <- tail(Capsule2U01CV10, n = 1)

Cylinder2U01CV10 <- objectsPositionU01CV10[objectsPositionU01CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U01CV10_check_Cylinder2 <- tail(Cylinder2U01CV10, n = 1)

SphereU01CV10 <- objectsPositionU01CV10[objectsPositionU01CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U01CV10_check_Sphere <- tail(SphereU01CV10, n = 1)

Cylinder_3U01CV10 <- objectsPositionU01CV10[objectsPositionU01CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U01CV10_check_Cylinder_3 <- tail(Cylinder_3U01CV10, n = 1)

U01CV10_check_total <- rbind(U01CV10_check_Cube2, U01CV10_check_Capsule, U01CV10_check_Cube_1,
                             U01CV10_check_Cube, U01CV10_check_Cylinder, U01CV10_check_Egg, 
                             U01CV10_check_Capsule2, U01CV10_check_Cylinder2, U01CV10_check_Sphere, 
                             U01CV10_check_Cylinder_3)
write.xlsx(objectsPositionU01CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU01CV10", append=TRUE)
write.xlsx(U01CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U01CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U02CV10 -------------------
## copio dati da JSON
U02CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_03_15_30_12_U02.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU02CV10<-U02CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU02CV10<-U02CV10[[2]][[1]]
objectsPositionU02CV10$Utente <- "U02CV"

## creo tabella per ogni oggetto
Cube2U02CV10 <- objectsPositionU02CV10[objectsPositionU02CV10$objPosition %like% "Cube2", ]
Cube2U02CV10$Utente <- "U02CV"
## controllo ultima posizione
U02CV10_check_Cube2 <- tail(Cube2U02CV10, n = 1)

CapsuleU02CV10 <- objectsPositionU02CV10[objectsPositionU02CV10$objPosition %like% "Capsule", ]
CapsuleU02CV10$Utente <- "U02CV"
## controllo ultima posizione
U02CV10_check_Capsule <- tail(CapsuleU02CV10, n = 1)

Cube_1U02CV10 <- objectsPositionU02CV10[objectsPositionU02CV10$objPosition %like% "Cube 1", ]
Cube_1U02CV10$Utente <- "U02CV"
## controllo ultima posizione
U02CV10_check_Cube_1 <- tail(Cube_1U02CV10, n = 1)

CubeU02CV10 <- objectsPositionU02CV10[objectsPositionU02CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U02CV10_check_Cube <- tail(CubeU02CV10, n = 1)

CylinderU02CV10 <- objectsPositionU02CV10[objectsPositionU02CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U02CV10_check_Cylinder <- tail(CylinderU02CV10, n = 1)

EggU02CV10 <- objectsPositionU02CV10[objectsPositionU02CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U02CV10_check_Egg <- tail(EggU02CV10, n = 1)

Capsule2U02CV10 <- objectsPositionU02CV10[objectsPositionU02CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U02CV10_check_Capsule2 <- tail(Capsule2U02CV10, n = 1)

Cylinder2U02CV10 <- objectsPositionU02CV10[objectsPositionU02CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U02CV10_check_Cylinder2 <- tail(Cylinder2U02CV10, n = 1)

SphereU02CV10 <- objectsPositionU02CV10[objectsPositionU02CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U02CV10_check_Sphere <- tail(SphereU02CV10, n = 1)

Cylinder_3U02CV10 <- objectsPositionU02CV10[objectsPositionU02CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U02CV10_check_Cylinder_3 <- tail(Cylinder_3U02CV10, n = 1)

U02CV10_check_total <- rbind(U02CV10_check_Cube2, U02CV10_check_Capsule, U02CV10_check_Cube_1,
                             U02CV10_check_Cube, U02CV10_check_Cylinder, U02CV10_check_Egg, 
                             U02CV10_check_Capsule2, U02CV10_check_Cylinder2, U02CV10_check_Sphere, 
                             U02CV10_check_Cylinder_3)
write.xlsx(objectsPositionU02CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU02CV10", append=TRUE)
write.xlsx(U02CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U02CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U03CV10 -------------------
## copio dati da JSON
U03CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_03_16_06_47_U03.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU03CV10<-U03CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU03CV10<-U03CV10[[2]][[1]]
objectsPositionU03CV10$Utente <- "U03CV"

## creo tabella per ogni oggetto
Cube2U03CV10 <- objectsPositionU03CV10[objectsPositionU03CV10$objPosition %like% "Cube2", ]
Cube2U03CV10$Utente <- "U03CV"
## controllo ultima posizione
U03CV10_check_Cube2 <- tail(Cube2U03CV10, n = 1)

CapsuleU03CV10 <- objectsPositionU03CV10[objectsPositionU03CV10$objPosition %like% "Capsule", ]
CapsuleU03CV10$Utente <- "U03CV"
## controllo ultima posizione
U03CV10_check_Capsule <- tail(CapsuleU03CV10, n = 1)

Cube_1U03CV10 <- objectsPositionU03CV10[objectsPositionU03CV10$objPosition %like% "Cube 1", ]
Cube_1U03CV10$Utente <- "U03CV"
## controllo ultima posizione
U03CV10_check_Cube_1 <- tail(Cube_1U03CV10, n = 1)

CubeU03CV10 <- objectsPositionU03CV10[objectsPositionU03CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U03CV10_check_Cube <- tail(CubeU03CV10, n = 1)

CylinderU03CV10 <- objectsPositionU03CV10[objectsPositionU03CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U03CV10_check_Cylinder <- tail(CylinderU03CV10, n = 1)

EggU03CV10 <- objectsPositionU03CV10[objectsPositionU03CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U03CV10_check_Egg <- tail(EggU03CV10, n = 1)

Capsule2U03CV10 <- objectsPositionU03CV10[objectsPositionU03CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U03CV10_check_Capsule2 <- tail(Capsule2U03CV10, n = 1)

Cylinder2U03CV10 <- objectsPositionU03CV10[objectsPositionU03CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U03CV10_check_Cylinder2 <- tail(Cylinder2U03CV10, n = 1)

SphereU03CV10 <- objectsPositionU03CV10[objectsPositionU03CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U03CV10_check_Sphere <- tail(SphereU03CV10, n = 1)

Cylinder_3U03CV10 <- objectsPositionU03CV10[objectsPositionU03CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U03CV10_check_Cylinder_3 <- tail(Cylinder_3U03CV10, n = 1)

U03CV10_check_total <- rbind(U03CV10_check_Cube2, U03CV10_check_Capsule, U03CV10_check_Cube_1,
                             U03CV10_check_Cube, U03CV10_check_Cylinder, U03CV10_check_Egg, 
                             U03CV10_check_Capsule2, U03CV10_check_Cylinder2, U03CV10_check_Sphere, 
                             U03CV10_check_Cylinder_3)
write.xlsx(objectsPositionU03CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU03CV10", append=TRUE)
write.xlsx(U03CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U03CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U04CV10 -------------------
## copio dati da JSON
U04CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_09_35_02_U04.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU04CV10<-U04CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU04CV10<-U04CV10[[2]][[1]]
objectsPositionU04CV10$Utente <- "U04CV"

## creo tabella per ogni oggetto
Cube2U04CV10 <- objectsPositionU04CV10[objectsPositionU04CV10$objPosition %like% "Cube2", ]
Cube2U04CV10$Utente <- "U04CV"
## controllo ultima posizione
U04CV10_check_Cube2 <- tail(Cube2U04CV10, n = 1)

CapsuleU04CV10 <- objectsPositionU04CV10[objectsPositionU04CV10$objPosition %like% "Capsule", ]
CapsuleU04CV10$Utente <- "U04CV"
## controllo ultima posizione
U04CV10_check_Capsule <- tail(CapsuleU04CV10, n = 1)

Cube_1U04CV10 <- objectsPositionU04CV10[objectsPositionU04CV10$objPosition %like% "Cube 1", ]
Cube_1U04CV10$Utente <- "U04CV"
## controllo ultima posizione
U04CV10_check_Cube_1 <- tail(Cube_1U04CV10, n = 1)

CubeU04CV10 <- objectsPositionU04CV10[objectsPositionU04CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U04CV10_check_Cube <- tail(CubeU04CV10, n = 1)

CylinderU04CV10 <- objectsPositionU04CV10[objectsPositionU04CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U04CV10_check_Cylinder <- tail(CylinderU04CV10, n = 1)

EggU04CV10 <- objectsPositionU04CV10[objectsPositionU04CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U04CV10_check_Egg <- tail(EggU04CV10, n = 1)

Capsule2U04CV10 <- objectsPositionU04CV10[objectsPositionU04CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U04CV10_check_Capsule2 <- tail(Capsule2U04CV10, n = 1)

Cylinder2U04CV10 <- objectsPositionU04CV10[objectsPositionU04CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U04CV10_check_Cylinder2 <- tail(Cylinder2U04CV10, n = 1)

SphereU04CV10 <- objectsPositionU04CV10[objectsPositionU04CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U04CV10_check_Sphere <- tail(SphereU04CV10, n = 1)

Cylinder_3U04CV10 <- objectsPositionU04CV10[objectsPositionU04CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U04CV10_check_Cylinder_3 <- tail(Cylinder_3U04CV10, n = 1)

U04CV10_check_total <- rbind(U04CV10_check_Cube2, U04CV10_check_Capsule, U04CV10_check_Cube_1,
                             U04CV10_check_Cube, U04CV10_check_Cylinder, U04CV10_check_Egg, 
                             U04CV10_check_Capsule2, U04CV10_check_Cylinder2, U04CV10_check_Sphere, 
                             U04CV10_check_Cylinder_3)
write.xlsx(objectsPositionU04CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU04CV10", append=TRUE)
write.xlsx(U04CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U04CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U05CV10 -------------------
## copio dati da JSON
U05CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_10_33_43_U05.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU05CV10<-U05CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU05CV10<-U05CV10[[2]][[1]]
objectsPositionU05CV10$Utente <- "U05CV"

## creo tabella per ogni oggetto
Cube2U05CV10 <- objectsPositionU05CV10[objectsPositionU05CV10$objPosition %like% "Cube2", ]
Cube2U05CV10$Utente <- "U05CV"
## controllo ultima posizione
U05CV10_check_Cube2 <- tail(Cube2U05CV10, n = 1)

CapsuleU05CV10 <- objectsPositionU05CV10[objectsPositionU05CV10$objPosition %like% "Capsule", ]
CapsuleU05CV10$Utente <- "U05CV"
## controllo ultima posizione
U05CV10_check_Capsule <- tail(CapsuleU05CV10, n = 1)

Cube_1U05CV10 <- objectsPositionU05CV10[objectsPositionU05CV10$objPosition %like% "Cube 1", ]
Cube_1U05CV10$Utente <- "U05CV"
## controllo ultima posizione
U05CV10_check_Cube_1 <- tail(Cube_1U05CV10, n = 1)

CubeU05CV10 <- objectsPositionU05CV10[objectsPositionU05CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U05CV10_check_Cube <- tail(CubeU05CV10, n = 1)

CylinderU05CV10 <- objectsPositionU05CV10[objectsPositionU05CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U05CV10_check_Cylinder <- tail(CylinderU05CV10, n = 1)

EggU05CV10 <- objectsPositionU05CV10[objectsPositionU05CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U05CV10_check_Egg <- tail(EggU05CV10, n = 1)

Capsule2U05CV10 <- objectsPositionU05CV10[objectsPositionU05CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U05CV10_check_Capsule2 <- tail(Capsule2U05CV10, n = 1)

Cylinder2U05CV10 <- objectsPositionU05CV10[objectsPositionU05CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U05CV10_check_Cylinder2 <- tail(Cylinder2U05CV10, n = 1)

SphereU05CV10 <- objectsPositionU05CV10[objectsPositionU05CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U05CV10_check_Sphere <- tail(SphereU05CV10, n = 1)

Cylinder_3U05CV10 <- objectsPositionU05CV10[objectsPositionU05CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U05CV10_check_Cylinder_3 <- tail(Cylinder_3U05CV10, n = 1)

U05CV10_check_total <- rbind(U05CV10_check_Cube2, U05CV10_check_Capsule, U05CV10_check_Cube_1,
                             U05CV10_check_Cube, U05CV10_check_Cylinder, U05CV10_check_Egg, 
                             U05CV10_check_Capsule2, U05CV10_check_Cylinder2, U05CV10_check_Sphere, 
                             U05CV10_check_Cylinder_3)
write.xlsx(objectsPositionU05CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU05CV10", append=TRUE)
write.xlsx(U05CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U05CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U06CV10 -------------------
## copio dati da JSON
U06CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_11_33_23_U06.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU06CV10<-U06CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU06CV10<-U06CV10[[2]][[1]]
objectsPositionU06CV10$Utente <- "U06CV"

## creo tabella per ogni oggetto
Cube2U06CV10 <- objectsPositionU06CV10[objectsPositionU06CV10$objPosition %like% "Cube2", ]
Cube2U06CV10$Utente <- "U06CV"
## controllo ultima posizione
U06CV10_check_Cube2 <- tail(Cube2U06CV10, n = 1)

CapsuleU06CV10 <- objectsPositionU06CV10[objectsPositionU06CV10$objPosition %like% "Capsule", ]
CapsuleU06CV10$Utente <- "U06CV"
## controllo ultima posizione
U06CV10_check_Capsule <- tail(CapsuleU06CV10, n = 1)

Cube_1U06CV10 <- objectsPositionU06CV10[objectsPositionU06CV10$objPosition %like% "Cube 1", ]
Cube_1U06CV10$Utente <- "U06CV"
## controllo ultima posizione
U06CV10_check_Cube_1 <- tail(Cube_1U06CV10, n = 1)

CubeU06CV10 <- objectsPositionU06CV10[objectsPositionU06CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U06CV10_check_Cube <- tail(CubeU06CV10, n = 1)

CylinderU06CV10 <- objectsPositionU06CV10[objectsPositionU06CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U06CV10_check_Cylinder <- tail(CylinderU06CV10, n = 1)

EggU06CV10 <- objectsPositionU06CV10[objectsPositionU06CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U06CV10_check_Egg <- tail(EggU06CV10, n = 1)

Capsule2U06CV10 <- objectsPositionU06CV10[objectsPositionU06CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U06CV10_check_Capsule2 <- tail(Capsule2U06CV10, n = 1)

Cylinder2U06CV10 <- objectsPositionU06CV10[objectsPositionU06CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U06CV10_check_Cylinder2 <- tail(Cylinder2U06CV10, n = 1)

SphereU06CV10 <- objectsPositionU06CV10[objectsPositionU06CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U06CV10_check_Sphere <- tail(SphereU06CV10, n = 1)

Cylinder_3U06CV10 <- objectsPositionU06CV10[objectsPositionU06CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U06CV10_check_Cylinder_3 <- tail(Cylinder_3U06CV10, n = 1)

U06CV10_check_total <- rbind(U06CV10_check_Cube2, U06CV10_check_Capsule, U06CV10_check_Cube_1,
                             U06CV10_check_Cube, U06CV10_check_Cylinder, U06CV10_check_Egg, 
                             U06CV10_check_Capsule2, U06CV10_check_Cylinder2, U06CV10_check_Sphere, 
                             U06CV10_check_Cylinder_3)
write.xlsx(objectsPositionU06CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU06CV10", append=TRUE)
write.xlsx(U06CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U06CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U07CV10 -------------------
## copio dati da JSON
U07CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_14_17_21_U07.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU07CV10<-U07CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU07CV10<-U07CV10[[2]][[1]]
objectsPositionU07CV10$Utente <- "U07CV"

## creo tabella per ogni oggetto
Cube2U07CV10 <- objectsPositionU07CV10[objectsPositionU07CV10$objPosition %like% "Cube2", ]
Cube2U07CV10$Utente <- "U07CV"
## controllo ultima posizione
U07CV10_check_Cube2 <- tail(Cube2U07CV10, n = 1)

CapsuleU07CV10 <- objectsPositionU07CV10[objectsPositionU07CV10$objPosition %like% "Capsule", ]
CapsuleU07CV10$Utente <- "U07CV"
## controllo ultima posizione
U07CV10_check_Capsule <- tail(CapsuleU07CV10, n = 1)

Cube_1U07CV10 <- objectsPositionU07CV10[objectsPositionU07CV10$objPosition %like% "Cube 1", ]
Cube_1U07CV10$Utente <- "U07CV"
## controllo ultima posizione
U07CV10_check_Cube_1 <- tail(Cube_1U07CV10, n = 1)

CubeU07CV10 <- objectsPositionU07CV10[objectsPositionU07CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U07CV10_check_Cube <- tail(CubeU07CV10, n = 1)

CylinderU07CV10 <- objectsPositionU07CV10[objectsPositionU07CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U07CV10_check_Cylinder <- tail(CylinderU07CV10, n = 1)

EggU07CV10 <- objectsPositionU07CV10[objectsPositionU07CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U07CV10_check_Egg <- tail(EggU07CV10, n = 1)

Capsule2U07CV10 <- objectsPositionU07CV10[objectsPositionU07CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U07CV10_check_Capsule2 <- tail(Capsule2U07CV10, n = 1)

Cylinder2U07CV10 <- objectsPositionU07CV10[objectsPositionU07CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U07CV10_check_Cylinder2 <- tail(Cylinder2U07CV10, n = 1)

SphereU07CV10 <- objectsPositionU07CV10[objectsPositionU07CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U07CV10_check_Sphere <- tail(SphereU07CV10, n = 1)

Cylinder_3U07CV10 <- objectsPositionU07CV10[objectsPositionU07CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U07CV10_check_Cylinder_3 <- tail(Cylinder_3U07CV10, n = 1)

U07CV10_check_total <- rbind(U07CV10_check_Cube2, U07CV10_check_Capsule, U07CV10_check_Cube_1,
                             U07CV10_check_Cube, U07CV10_check_Cylinder, U07CV10_check_Egg, 
                             U07CV10_check_Capsule2, U07CV10_check_Cylinder2, U07CV10_check_Sphere, 
                             U07CV10_check_Cylinder_3)
write.xlsx(objectsPositionU07CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU07CV10", append=TRUE)
write.xlsx(U07CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U07CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U08CV10 -------------------
## copio dati da JSON
U08CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_15_41_51_U08.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU08CV10<-U08CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU08CV10<-U08CV10[[2]][[1]]
objectsPositionU08CV10$Utente <- "U08CV"

## creo tabella per ogni oggetto
Cube2U08CV10 <- objectsPositionU08CV10[objectsPositionU08CV10$objPosition %like% "Cube2", ]
Cube2U08CV10$Utente <- "U08CV"
## controllo ultima posizione
U08CV10_check_Cube2 <- tail(Cube2U08CV10, n = 1)

CapsuleU08CV10 <- objectsPositionU08CV10[objectsPositionU08CV10$objPosition %like% "Capsule", ]
CapsuleU08CV10$Utente <- "U08CV"
## controllo ultima posizione
U08CV10_check_Capsule <- tail(CapsuleU08CV10, n = 1)

Cube_1U08CV10 <- objectsPositionU08CV10[objectsPositionU08CV10$objPosition %like% "Cube 1", ]
Cube_1U08CV10$Utente <- "U08CV"
## controllo ultima posizione
U08CV10_check_Cube_1 <- tail(Cube_1U08CV10, n = 1)

CubeU08CV10 <- objectsPositionU08CV10[objectsPositionU08CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U08CV10_check_Cube <- tail(CubeU08CV10, n = 1)

CylinderU08CV10 <- objectsPositionU08CV10[objectsPositionU08CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U08CV10_check_Cylinder <- tail(CylinderU08CV10, n = 1)

EggU08CV10 <- objectsPositionU08CV10[objectsPositionU08CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U08CV10_check_Egg <- tail(EggU08CV10, n = 1)

Capsule2U08CV10 <- objectsPositionU08CV10[objectsPositionU08CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U08CV10_check_Capsule2 <- tail(Capsule2U08CV10, n = 1)

Cylinder2U08CV10 <- objectsPositionU08CV10[objectsPositionU08CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U08CV10_check_Cylinder2 <- tail(Cylinder2U08CV10, n = 1)

SphereU08CV10 <- objectsPositionU08CV10[objectsPositionU08CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U08CV10_check_Sphere <- tail(SphereU08CV10, n = 1)

Cylinder_3U08CV10 <- objectsPositionU08CV10[objectsPositionU08CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U08CV10_check_Cylinder_3 <- tail(Cylinder_3U08CV10, n = 1)

U08CV10_check_total <- rbind(U08CV10_check_Cube2, U08CV10_check_Capsule, U08CV10_check_Cube_1,
                             U08CV10_check_Cube, U08CV10_check_Cylinder, U08CV10_check_Egg, 
                             U08CV10_check_Capsule2, U08CV10_check_Cylinder2, U08CV10_check_Sphere, 
                             U08CV10_check_Cylinder_3)
write.xlsx(objectsPositionU08CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU08CV10", append=TRUE)
write.xlsx(U08CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U08CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U09CV10 -------------------
## copio dati da JSON
U09CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_16_24_37_U09.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU09CV10<-U09CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU09CV10<-U09CV10[[2]][[1]]
objectsPositionU09CV10$Utente <- "U09CV"

## creo tabella per ogni oggetto
Cube2U09CV10 <- objectsPositionU09CV10[objectsPositionU09CV10$objPosition %like% "Cube2", ]
Cube2U09CV10$Utente <- "U09CV"
## controllo ultima posizione
U09CV10_check_Cube2 <- tail(Cube2U09CV10, n = 1)

CapsuleU09CV10 <- objectsPositionU09CV10[objectsPositionU09CV10$objPosition %like% "Capsule", ]
CapsuleU09CV10$Utente <- "U09CV"
## controllo ultima posizione
U09CV10_check_Capsule <- tail(CapsuleU09CV10, n = 1)

Cube_1U09CV10 <- objectsPositionU09CV10[objectsPositionU09CV10$objPosition %like% "Cube 1", ]
Cube_1U09CV10$Utente <- "U09CV"
## controllo ultima posizione
U09CV10_check_Cube_1 <- tail(Cube_1U09CV10, n = 1)

CubeU09CV10 <- objectsPositionU09CV10[objectsPositionU09CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U09CV10_check_Cube <- tail(CubeU09CV10, n = 1)

CylinderU09CV10 <- objectsPositionU09CV10[objectsPositionU09CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U09CV10_check_Cylinder <- tail(CylinderU09CV10, n = 1)

EggU09CV10 <- objectsPositionU09CV10[objectsPositionU09CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U09CV10_check_Egg <- tail(EggU09CV10, n = 1)

Capsule2U09CV10 <- objectsPositionU09CV10[objectsPositionU09CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U09CV10_check_Capsule2 <- tail(Capsule2U09CV10, n = 1)

Cylinder2U09CV10 <- objectsPositionU09CV10[objectsPositionU09CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U09CV10_check_Cylinder2 <- tail(Cylinder2U09CV10, n = 1)

SphereU09CV10 <- objectsPositionU09CV10[objectsPositionU09CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U09CV10_check_Sphere <- tail(SphereU09CV10, n = 1)

Cylinder_3U09CV10 <- objectsPositionU09CV10[objectsPositionU09CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U09CV10_check_Cylinder_3 <- tail(Cylinder_3U09CV10, n = 1)

U09CV10_check_total <- rbind(U09CV10_check_Cube2, U09CV10_check_Capsule, U09CV10_check_Cube_1,
                             U09CV10_check_Cube, U09CV10_check_Cylinder, U09CV10_check_Egg, 
                             U09CV10_check_Capsule2, U09CV10_check_Cylinder2, U09CV10_check_Sphere, 
                             U09CV10_check_Cylinder_3)
write.xlsx(objectsPositionU09CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU09CV10", append=TRUE)
write.xlsx(U09CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U09CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U10CV10 -------------------
## copio dati da JSON
U10CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_05_09_53_01_U10.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU10CV10<-U10CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU10CV10<-U10CV10[[2]][[1]]
objectsPositionU10CV10$Utente <- "U10CV"

## creo tabella per ogni oggetto
Cube2U10CV10 <- objectsPositionU10CV10[objectsPositionU10CV10$objPosition %like% "Cube2", ]
Cube2U10CV10$Utente <- "U10CV"
## controllo ultima posizione
U10CV10_check_Cube2 <- tail(Cube2U10CV10, n = 1)

CapsuleU10CV10 <- objectsPositionU10CV10[objectsPositionU10CV10$objPosition %like% "Capsule", ]
CapsuleU10CV10$Utente <- "U10CV"
## controllo ultima posizione
U10CV10_check_Capsule <- tail(CapsuleU10CV10, n = 1)

Cube_1U10CV10 <- objectsPositionU10CV10[objectsPositionU10CV10$objPosition %like% "Cube 1", ]
Cube_1U10CV10$Utente <- "U10CV"
## controllo ultima posizione
U10CV10_check_Cube_1 <- tail(Cube_1U10CV10, n = 1)

CubeU10CV10 <- objectsPositionU10CV10[objectsPositionU10CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U10CV10_check_Cube <- tail(CubeU10CV10, n = 1)

CylinderU10CV10 <- objectsPositionU10CV10[objectsPositionU10CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U10CV10_check_Cylinder <- tail(CylinderU10CV10, n = 1)

EggU10CV10 <- objectsPositionU10CV10[objectsPositionU10CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U10CV10_check_Egg <- tail(EggU10CV10, n = 1)

Capsule2U10CV10 <- objectsPositionU10CV10[objectsPositionU10CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U10CV10_check_Capsule2 <- tail(Capsule2U10CV10, n = 1)

Cylinder2U10CV10 <- objectsPositionU10CV10[objectsPositionU10CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U10CV10_check_Cylinder2 <- tail(Cylinder2U10CV10, n = 1)

SphereU10CV10 <- objectsPositionU10CV10[objectsPositionU10CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U10CV10_check_Sphere <- tail(SphereU10CV10, n = 1)

Cylinder_3U10CV10 <- objectsPositionU10CV10[objectsPositionU10CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U10CV10_check_Cylinder_3 <- tail(Cylinder_3U10CV10, n = 1)

U10CV10_check_total <- rbind(U10CV10_check_Cube2, U10CV10_check_Capsule, U10CV10_check_Cube_1,
                             U10CV10_check_Cube, U10CV10_check_Cylinder, U10CV10_check_Egg, 
                             U10CV10_check_Capsule2, U10CV10_check_Cylinder2, U10CV10_check_Sphere, 
                             U10CV10_check_Cylinder_3)
write.xlsx(objectsPositionU10CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU10CV10", append=TRUE)
write.xlsx(U10CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U10CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U11CV10 -------------------
## copio dati da JSON
U11CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_05_11_00_49_U11.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU11CV10<-U11CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU11CV10<-U11CV10[[2]][[1]]
objectsPositionU11CV10$Utente <- "U11CV"

## creo tabella per ogni oggetto
Cube2U11CV10 <- objectsPositionU11CV10[objectsPositionU11CV10$objPosition %like% "Cube2", ]
Cube2U11CV10$Utente <- "U11CV"
## controllo ultima posizione
U11CV10_check_Cube2 <- tail(Cube2U11CV10, n = 1)

CapsuleU11CV10 <- objectsPositionU11CV10[objectsPositionU11CV10$objPosition %like% "Capsule", ]
CapsuleU11CV10$Utente <- "U11CV"
## controllo ultima posizione
U11CV10_check_Capsule <- tail(CapsuleU11CV10, n = 1)

Cube_1U11CV10 <- objectsPositionU11CV10[objectsPositionU11CV10$objPosition %like% "Cube 1", ]
Cube_1U11CV10$Utente <- "U11CV"
## controllo ultima posizione
U11CV10_check_Cube_1 <- tail(Cube_1U11CV10, n = 1)

CubeU11CV10 <- objectsPositionU11CV10[objectsPositionU11CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U11CV10_check_Cube <- tail(CubeU11CV10, n = 1)

CylinderU11CV10 <- objectsPositionU11CV10[objectsPositionU11CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U11CV10_check_Cylinder <- tail(CylinderU11CV10, n = 1)

EggU11CV10 <- objectsPositionU11CV10[objectsPositionU11CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U11CV10_check_Egg <- tail(EggU11CV10, n = 1)

Capsule2U11CV10 <- objectsPositionU11CV10[objectsPositionU11CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U11CV10_check_Capsule2 <- tail(Capsule2U11CV10, n = 1)

Cylinder2U11CV10 <- objectsPositionU11CV10[objectsPositionU11CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U11CV10_check_Cylinder2 <- tail(Cylinder2U11CV10, n = 1)

SphereU11CV10 <- objectsPositionU11CV10[objectsPositionU11CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U11CV10_check_Sphere <- tail(SphereU11CV10, n = 1)

Cylinder_3U11CV10 <- objectsPositionU11CV10[objectsPositionU11CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U11CV10_check_Cylinder_3 <- tail(Cylinder_3U11CV10, n = 1)

U11CV10_check_total <- rbind(U11CV10_check_Cube2, U11CV10_check_Capsule, U11CV10_check_Cube_1,
                             U11CV10_check_Cube, U11CV10_check_Cylinder, U11CV10_check_Egg, 
                             U11CV10_check_Capsule2, U11CV10_check_Cylinder2, U11CV10_check_Sphere, 
                             U11CV10_check_Cylinder_3)
write.xlsx(objectsPositionU11CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU11CV10", append=TRUE)
write.xlsx(U11CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U11CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U12CV10 -------------------
## copio dati da JSON
U12CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_05_11_53_07_U12.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU12CV10<-U12CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU12CV10<-U12CV10[[2]][[1]]
objectsPositionU12CV10$Utente <- "U12CV"

## creo tabella per ogni oggetto
Cube2U12CV10 <- objectsPositionU12CV10[objectsPositionU12CV10$objPosition %like% "Cube2", ]
Cube2U12CV10$Utente <- "U12CV"
## controllo ultima posizione
U12CV10_check_Cube2 <- tail(Cube2U12CV10, n = 1)

CapsuleU12CV10 <- objectsPositionU12CV10[objectsPositionU12CV10$objPosition %like% "Capsule", ]
CapsuleU12CV10$Utente <- "U12CV"
## controllo ultima posizione
U12CV10_check_Capsule <- tail(CapsuleU12CV10, n = 1)

Cube_1U12CV10 <- objectsPositionU12CV10[objectsPositionU12CV10$objPosition %like% "Cube 1", ]
Cube_1U12CV10$Utente <- "U12CV"
## controllo ultima posizione
U12CV10_check_Cube_1 <- tail(Cube_1U12CV10, n = 1)

CubeU12CV10 <- objectsPositionU12CV10[objectsPositionU12CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U12CV10_check_Cube <- tail(CubeU12CV10, n = 1)

CylinderU12CV10 <- objectsPositionU12CV10[objectsPositionU12CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U12CV10_check_Cylinder <- tail(CylinderU12CV10, n = 1)

EggU12CV10 <- objectsPositionU12CV10[objectsPositionU12CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U12CV10_check_Egg <- tail(EggU12CV10, n = 1)

Capsule2U12CV10 <- objectsPositionU12CV10[objectsPositionU12CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U12CV10_check_Capsule2 <- tail(Capsule2U12CV10, n = 1)

Cylinder2U12CV10 <- objectsPositionU12CV10[objectsPositionU12CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U12CV10_check_Cylinder2 <- tail(Cylinder2U12CV10, n = 1)

SphereU12CV10 <- objectsPositionU12CV10[objectsPositionU12CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U12CV10_check_Sphere <- tail(SphereU12CV10, n = 1)

Cylinder_3U12CV10 <- objectsPositionU12CV10[objectsPositionU12CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U12CV10_check_Cylinder_3 <- tail(Cylinder_3U12CV10, n = 1)

U12CV10_check_total <- rbind(U12CV10_check_Cube2, U12CV10_check_Capsule, U12CV10_check_Cube_1,
                             U12CV10_check_Cube, U12CV10_check_Cylinder, U12CV10_check_Egg, 
                             U12CV10_check_Capsule2, U12CV10_check_Cylinder2, U12CV10_check_Sphere, 
                             U12CV10_check_Cylinder_3)
write.xlsx(objectsPositionU12CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU12CV10", append=TRUE)
write.xlsx(U12CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U12CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U13CV10 -------------------
## copio dati da JSON
U13CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_08_10_57_39_U13.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU13CV10<-U13CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU13CV10<-U13CV10[[2]][[1]]
objectsPositionU13CV10$Utente <- "U13CV"

## creo tabella per ogni oggetto
Cube2U13CV10 <- objectsPositionU13CV10[objectsPositionU13CV10$objPosition %like% "Cube2", ]
Cube2U13CV10$Utente <- "U13CV"
## controllo ultima posizione
U13CV10_check_Cube2 <- tail(Cube2U13CV10, n = 1)

CapsuleU13CV10 <- objectsPositionU13CV10[objectsPositionU13CV10$objPosition %like% "Capsule", ]
CapsuleU13CV10$Utente <- "U13CV"
## controllo ultima posizione
U13CV10_check_Capsule <- tail(CapsuleU13CV10, n = 1)

Cube_1U13CV10 <- objectsPositionU13CV10[objectsPositionU13CV10$objPosition %like% "Cube 1", ]
Cube_1U13CV10$Utente <- "U13CV"
## controllo ultima posizione
U13CV10_check_Cube_1 <- tail(Cube_1U13CV10, n = 1)

CubeU13CV10 <- objectsPositionU13CV10[objectsPositionU13CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U13CV10_check_Cube <- tail(CubeU13CV10, n = 1)

CylinderU13CV10 <- objectsPositionU13CV10[objectsPositionU13CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U13CV10_check_Cylinder <- tail(CylinderU13CV10, n = 1)

EggU13CV10 <- objectsPositionU13CV10[objectsPositionU13CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U13CV10_check_Egg <- tail(EggU13CV10, n = 1)

Capsule2U13CV10 <- objectsPositionU13CV10[objectsPositionU13CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U13CV10_check_Capsule2 <- tail(Capsule2U13CV10, n = 1)

Cylinder2U13CV10 <- objectsPositionU13CV10[objectsPositionU13CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U13CV10_check_Cylinder2 <- tail(Cylinder2U13CV10, n = 1)

SphereU13CV10 <- objectsPositionU13CV10[objectsPositionU13CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U13CV10_check_Sphere <- tail(SphereU13CV10, n = 1)

Cylinder_3U13CV10 <- objectsPositionU13CV10[objectsPositionU13CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U13CV10_check_Cylinder_3 <- tail(Cylinder_3U13CV10, n = 1)

U13CV10_check_total <- rbind(U13CV10_check_Cube2, U13CV10_check_Capsule, U13CV10_check_Cube_1,
                             U13CV10_check_Cube, U13CV10_check_Cylinder, U13CV10_check_Egg, 
                             U13CV10_check_Capsule2, U13CV10_check_Cylinder2, U13CV10_check_Sphere, 
                             U13CV10_check_Cylinder_3)
write.xlsx(objectsPositionU13CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU13CV10", append=TRUE)
write.xlsx(U13CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U13CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U14CV10 -------------------
## copio dati da JSON
U14CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_08_11_49_05_U14.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU14CV10<-U14CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU14CV10<-U14CV10[[2]][[1]]
objectsPositionU14CV10$Utente <- "U14CV"

## creo tabella per ogni oggetto
Cube2U14CV10 <- objectsPositionU14CV10[objectsPositionU14CV10$objPosition %like% "Cube2", ]
Cube2U14CV10$Utente <- "U14CV"
## controllo ultima posizione
U14CV10_check_Cube2 <- tail(Cube2U14CV10, n = 1)

CapsuleU14CV10 <- objectsPositionU14CV10[objectsPositionU14CV10$objPosition %like% "Capsule", ]
CapsuleU14CV10$Utente <- "U14CV"
## controllo ultima posizione
U14CV10_check_Capsule <- tail(CapsuleU14CV10, n = 1)

Cube_1U14CV10 <- objectsPositionU14CV10[objectsPositionU14CV10$objPosition %like% "Cube 1", ]
Cube_1U14CV10$Utente <- "U14CV"
## controllo ultima posizione
U14CV10_check_Cube_1 <- tail(Cube_1U14CV10, n = 1)

CubeU14CV10 <- objectsPositionU14CV10[objectsPositionU14CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U14CV10_check_Cube <- tail(CubeU14CV10, n = 1)

CylinderU14CV10 <- objectsPositionU14CV10[objectsPositionU14CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U14CV10_check_Cylinder <- tail(CylinderU14CV10, n = 1)

EggU14CV10 <- objectsPositionU14CV10[objectsPositionU14CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U14CV10_check_Egg <- tail(EggU14CV10, n = 1)

Capsule2U14CV10 <- objectsPositionU14CV10[objectsPositionU14CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U14CV10_check_Capsule2 <- tail(Capsule2U14CV10, n = 1)

Cylinder2U14CV10 <- objectsPositionU14CV10[objectsPositionU14CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U14CV10_check_Cylinder2 <- tail(Cylinder2U14CV10, n = 1)

SphereU14CV10 <- objectsPositionU14CV10[objectsPositionU14CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U14CV10_check_Sphere <- tail(SphereU14CV10, n = 1)

Cylinder_3U14CV10 <- objectsPositionU14CV10[objectsPositionU14CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U14CV10_check_Cylinder_3 <- tail(Cylinder_3U14CV10, n = 1)

U14CV10_check_total <- rbind(U14CV10_check_Cube2, U14CV10_check_Capsule, U14CV10_check_Cube_1,
                             U14CV10_check_Cube, U14CV10_check_Cylinder, U14CV10_check_Egg, 
                             U14CV10_check_Capsule2, U14CV10_check_Cylinder2, U14CV10_check_Sphere, 
                             U14CV10_check_Cylinder_3)
write.xlsx(objectsPositionU14CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU14CV10", append=TRUE)
write.xlsx(U14CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U14CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U15CV10 -------------------
## copio dati da JSON
U15CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_08_15_19_39_U15.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU15CV10<-U15CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU15CV10<-U15CV10[[2]][[1]]
objectsPositionU15CV10$Utente <- "U15CV"

## creo tabella per ogni oggetto
Cube2U15CV10 <- objectsPositionU15CV10[objectsPositionU15CV10$objPosition %like% "Cube2", ]
Cube2U15CV10$Utente <- "U15CV"
## controllo ultima posizione
U15CV10_check_Cube2 <- tail(Cube2U15CV10, n = 1)

CapsuleU15CV10 <- objectsPositionU15CV10[objectsPositionU15CV10$objPosition %like% "Capsule", ]
CapsuleU15CV10$Utente <- "U15CV"
## controllo ultima posizione
U15CV10_check_Capsule <- tail(CapsuleU15CV10, n = 1)

Cube_1U15CV10 <- objectsPositionU15CV10[objectsPositionU15CV10$objPosition %like% "Cube 1", ]
Cube_1U15CV10$Utente <- "U15CV"
## controllo ultima posizione
U15CV10_check_Cube_1 <- tail(Cube_1U15CV10, n = 1)

CubeU15CV10 <- objectsPositionU15CV10[objectsPositionU15CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U15CV10_check_Cube <- tail(CubeU15CV10, n = 1)

CylinderU15CV10 <- objectsPositionU15CV10[objectsPositionU15CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U15CV10_check_Cylinder <- tail(CylinderU15CV10, n = 1)

EggU15CV10 <- objectsPositionU15CV10[objectsPositionU15CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U15CV10_check_Egg <- tail(EggU15CV10, n = 1)

Capsule2U15CV10 <- objectsPositionU15CV10[objectsPositionU15CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U15CV10_check_Capsule2 <- tail(Capsule2U15CV10, n = 1)

Cylinder2U15CV10 <- objectsPositionU15CV10[objectsPositionU15CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U15CV10_check_Cylinder2 <- tail(Cylinder2U15CV10, n = 1)

SphereU15CV10 <- objectsPositionU15CV10[objectsPositionU15CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U15CV10_check_Sphere <- tail(SphereU15CV10, n = 1)

Cylinder_3U15CV10 <- objectsPositionU15CV10[objectsPositionU15CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U15CV10_check_Cylinder_3 <- tail(Cylinder_3U15CV10, n = 1)

U15CV10_check_total <- rbind(U15CV10_check_Cube2, U15CV10_check_Capsule, U15CV10_check_Cube_1,
                             U15CV10_check_Cube, U15CV10_check_Cylinder, U15CV10_check_Egg, 
                             U15CV10_check_Capsule2, U15CV10_check_Cylinder2, U15CV10_check_Sphere, 
                             U15CV10_check_Cylinder_3)
write.xlsx(objectsPositionU15CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU15CV10", append=TRUE)
write.xlsx(U15CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U15CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U16CV10 -------------------
## copio dati da JSON
U16CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_08_16_31_44_U16.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU16CV10<-U16CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU16CV10<-U16CV10[[2]][[1]]
objectsPositionU16CV10$Utente <- "U16CV"

## creo tabella per ogni oggetto
Cube2U16CV10 <- objectsPositionU16CV10[objectsPositionU16CV10$objPosition %like% "Cube2", ]
Cube2U16CV10$Utente <- "U16CV"
## controllo ultima posizione
U16CV10_check_Cube2 <- tail(Cube2U16CV10, n = 1)

CapsuleU16CV10 <- objectsPositionU16CV10[objectsPositionU16CV10$objPosition %like% "Capsule", ]
CapsuleU16CV10$Utente <- "U16CV"
## controllo ultima posizione
U16CV10_check_Capsule <- tail(CapsuleU16CV10, n = 1)

Cube_1U16CV10 <- objectsPositionU16CV10[objectsPositionU16CV10$objPosition %like% "Cube 1", ]
Cube_1U16CV10$Utente <- "U16CV"
## controllo ultima posizione
U16CV10_check_Cube_1 <- tail(Cube_1U16CV10, n = 1)

CubeU16CV10 <- objectsPositionU16CV10[objectsPositionU16CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U16CV10_check_Cube <- tail(CubeU16CV10, n = 1)

CylinderU16CV10 <- objectsPositionU16CV10[objectsPositionU16CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U16CV10_check_Cylinder <- tail(CylinderU16CV10, n = 1)

EggU16CV10 <- objectsPositionU16CV10[objectsPositionU16CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U16CV10_check_Egg <- tail(EggU16CV10, n = 1)

Capsule2U16CV10 <- objectsPositionU16CV10[objectsPositionU16CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U16CV10_check_Capsule2 <- tail(Capsule2U16CV10, n = 1)

Cylinder2U16CV10 <- objectsPositionU16CV10[objectsPositionU16CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U16CV10_check_Cylinder2 <- tail(Cylinder2U16CV10, n = 1)

SphereU16CV10 <- objectsPositionU16CV10[objectsPositionU16CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U16CV10_check_Sphere <- tail(SphereU16CV10, n = 1)

Cylinder_3U16CV10 <- objectsPositionU16CV10[objectsPositionU16CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U16CV10_check_Cylinder_3 <- tail(Cylinder_3U16CV10, n = 1)

U16CV10_check_total <- rbind(U16CV10_check_Cube2, U16CV10_check_Capsule, U16CV10_check_Cube_1,
                             U16CV10_check_Cube, U16CV10_check_Cylinder, U16CV10_check_Egg, 
                             U16CV10_check_Capsule2, U16CV10_check_Cylinder2, U16CV10_check_Sphere, 
                             U16CV10_check_Cylinder_3)
write.xlsx(objectsPositionU16CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU16CV10", append=TRUE)
write.xlsx(U16CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U16CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U17CV10 -------------------
## copio dati da JSON
U17CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_09_35_46_U17.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU17CV10<-U17CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU17CV10<-U17CV10[[2]][[1]]
objectsPositionU17CV10$Utente <- "U17CV"

## creo tabella per ogni oggetto
Cube2U17CV10 <- objectsPositionU17CV10[objectsPositionU17CV10$objPosition %like% "Cube2", ]
Cube2U17CV10$Utente <- "U17CV"
## controllo ultima posizione
U17CV10_check_Cube2 <- tail(Cube2U17CV10, n = 1)

CapsuleU17CV10 <- objectsPositionU17CV10[objectsPositionU17CV10$objPosition %like% "Capsule", ]
CapsuleU17CV10$Utente <- "U17CV"
## controllo ultima posizione
U17CV10_check_Capsule <- tail(CapsuleU17CV10, n = 1)

Cube_1U17CV10 <- objectsPositionU17CV10[objectsPositionU17CV10$objPosition %like% "Cube 1", ]
Cube_1U17CV10$Utente <- "U17CV"
## controllo ultima posizione
U17CV10_check_Cube_1 <- tail(Cube_1U17CV10, n = 1)

CubeU17CV10 <- objectsPositionU17CV10[objectsPositionU17CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U17CV10_check_Cube <- tail(CubeU17CV10, n = 1)

CylinderU17CV10 <- objectsPositionU17CV10[objectsPositionU17CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U17CV10_check_Cylinder <- tail(CylinderU17CV10, n = 1)

EggU17CV10 <- objectsPositionU17CV10[objectsPositionU17CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U17CV10_check_Egg <- tail(EggU17CV10, n = 1)

Capsule2U17CV10 <- objectsPositionU17CV10[objectsPositionU17CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U17CV10_check_Capsule2 <- tail(Capsule2U17CV10, n = 1)

Cylinder2U17CV10 <- objectsPositionU17CV10[objectsPositionU17CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U17CV10_check_Cylinder2 <- tail(Cylinder2U17CV10, n = 1)

SphereU17CV10 <- objectsPositionU17CV10[objectsPositionU17CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U17CV10_check_Sphere <- tail(SphereU17CV10, n = 1)

Cylinder_3U17CV10 <- objectsPositionU17CV10[objectsPositionU17CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U17CV10_check_Cylinder_3 <- tail(Cylinder_3U17CV10, n = 1)

U17CV10_check_total <- rbind(U17CV10_check_Cube2, U17CV10_check_Capsule, U17CV10_check_Cube_1,
                             U17CV10_check_Cube, U17CV10_check_Cylinder, U17CV10_check_Egg, 
                             U17CV10_check_Capsule2, U17CV10_check_Cylinder2, U17CV10_check_Sphere, 
                             U17CV10_check_Cylinder_3)
write.xlsx(objectsPositionU17CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU17CV10", append=TRUE)
write.xlsx(U17CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U17CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U18CV10 -------------------
## copio dati da JSON
U18CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_10_56_51_U18.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU18CV10<-U18CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU18CV10<-U18CV10[[2]][[1]]
objectsPositionU18CV10$Utente <- "U18CV"

## creo tabella per ogni oggetto
Cube2U18CV10 <- objectsPositionU18CV10[objectsPositionU18CV10$objPosition %like% "Cube2", ]
Cube2U18CV10$Utente <- "U18CV"
## controllo ultima posizione
U18CV10_check_Cube2 <- tail(Cube2U18CV10, n = 1)

CapsuleU18CV10 <- objectsPositionU18CV10[objectsPositionU18CV10$objPosition %like% "Capsule", ]
CapsuleU18CV10$Utente <- "U18CV"
## controllo ultima posizione
U18CV10_check_Capsule <- tail(CapsuleU18CV10, n = 1)

Cube_1U18CV10 <- objectsPositionU18CV10[objectsPositionU18CV10$objPosition %like% "Cube 1", ]
Cube_1U18CV10$Utente <- "U18CV"
## controllo ultima posizione
U18CV10_check_Cube_1 <- tail(Cube_1U18CV10, n = 1)

CubeU18CV10 <- objectsPositionU18CV10[objectsPositionU18CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U18CV10_check_Cube <- tail(CubeU18CV10, n = 1)

CylinderU18CV10 <- objectsPositionU18CV10[objectsPositionU18CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U18CV10_check_Cylinder <- tail(CylinderU18CV10, n = 1)

EggU18CV10 <- objectsPositionU18CV10[objectsPositionU18CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U18CV10_check_Egg <- tail(EggU18CV10, n = 1)

Capsule2U18CV10 <- objectsPositionU18CV10[objectsPositionU18CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U18CV10_check_Capsule2 <- tail(Capsule2U18CV10, n = 1)

Cylinder2U18CV10 <- objectsPositionU18CV10[objectsPositionU18CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U18CV10_check_Cylinder2 <- tail(Cylinder2U18CV10, n = 1)

SphereU18CV10 <- objectsPositionU18CV10[objectsPositionU18CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U18CV10_check_Sphere <- tail(SphereU18CV10, n = 1)

Cylinder_3U18CV10 <- objectsPositionU18CV10[objectsPositionU18CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U18CV10_check_Cylinder_3 <- tail(Cylinder_3U18CV10, n = 1)

U18CV10_check_total <- rbind(U18CV10_check_Cube2, U18CV10_check_Capsule, U18CV10_check_Cube_1,
                             U18CV10_check_Cube, U18CV10_check_Cylinder, U18CV10_check_Egg, 
                             U18CV10_check_Capsule2, U18CV10_check_Cylinder2, U18CV10_check_Sphere, 
                             U18CV10_check_Cylinder_3)
write.xlsx(objectsPositionU18CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU18CV10", append=TRUE)
write.xlsx(U18CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U18CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U19CV10 -------------------
## copio dati da JSON
U19CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_11_42_57_U19.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU19CV10<-U19CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU19CV10<-U19CV10[[2]][[1]]
objectsPositionU19CV10$Utente <- "U19CV"

## creo tabella per ogni oggetto
Cube2U19CV10 <- objectsPositionU19CV10[objectsPositionU19CV10$objPosition %like% "Cube2", ]
Cube2U19CV10$Utente <- "U19CV"
## controllo ultima posizione
U19CV10_check_Cube2 <- tail(Cube2U19CV10, n = 1)

CapsuleU19CV10 <- objectsPositionU19CV10[objectsPositionU19CV10$objPosition %like% "Capsule", ]
CapsuleU19CV10$Utente <- "U19CV"
## controllo ultima posizione
U19CV10_check_Capsule <- tail(CapsuleU19CV10, n = 1)

Cube_1U19CV10 <- objectsPositionU19CV10[objectsPositionU19CV10$objPosition %like% "Cube 1", ]
Cube_1U19CV10$Utente <- "U19CV"
## controllo ultima posizione
U19CV10_check_Cube_1 <- tail(Cube_1U19CV10, n = 1)

CubeU19CV10 <- objectsPositionU19CV10[objectsPositionU19CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U19CV10_check_Cube <- tail(CubeU19CV10, n = 1)

CylinderU19CV10 <- objectsPositionU19CV10[objectsPositionU19CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U19CV10_check_Cylinder <- tail(CylinderU19CV10, n = 1)

EggU19CV10 <- objectsPositionU19CV10[objectsPositionU19CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U19CV10_check_Egg <- tail(EggU19CV10, n = 1)

Capsule2U19CV10 <- objectsPositionU19CV10[objectsPositionU19CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U19CV10_check_Capsule2 <- tail(Capsule2U19CV10, n = 1)

Cylinder2U19CV10 <- objectsPositionU19CV10[objectsPositionU19CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U19CV10_check_Cylinder2 <- tail(Cylinder2U19CV10, n = 1)

SphereU19CV10 <- objectsPositionU19CV10[objectsPositionU19CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U19CV10_check_Sphere <- tail(SphereU19CV10, n = 1)

Cylinder_3U19CV10 <- objectsPositionU19CV10[objectsPositionU19CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U19CV10_check_Cylinder_3 <- tail(Cylinder_3U19CV10, n = 1)

U19CV10_check_total <- rbind(U19CV10_check_Cube2, U19CV10_check_Capsule, U19CV10_check_Cube_1,
                             U19CV10_check_Cube, U19CV10_check_Cylinder, U19CV10_check_Egg, 
                             U19CV10_check_Capsule2, U19CV10_check_Cylinder2, U19CV10_check_Sphere, 
                             U19CV10_check_Cylinder_3)
write.xlsx(objectsPositionU19CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU19CV10", append=TRUE)
write.xlsx(U19CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U19CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U20CV10 -------------------
## copio dati da JSON
U20CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_14_21_00_U20.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU20CV10<-U20CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU20CV10<-U20CV10[[2]][[1]]
objectsPositionU20CV10$Utente <- "U20CV"

## creo tabella per ogni oggetto
Cube2U20CV10 <- objectsPositionU20CV10[objectsPositionU20CV10$objPosition %like% "Cube2", ]
Cube2U20CV10$Utente <- "U20CV"
## controllo ultima posizione
U20CV10_check_Cube2 <- tail(Cube2U20CV10, n = 1)

CapsuleU20CV10 <- objectsPositionU20CV10[objectsPositionU20CV10$objPosition %like% "Capsule", ]
CapsuleU20CV10$Utente <- "U20CV"
## controllo ultima posizione
U20CV10_check_Capsule <- tail(CapsuleU20CV10, n = 1)

Cube_1U20CV10 <- objectsPositionU20CV10[objectsPositionU20CV10$objPosition %like% "Cube 1", ]
Cube_1U20CV10$Utente <- "U20CV"
## controllo ultima posizione
U20CV10_check_Cube_1 <- tail(Cube_1U20CV10, n = 1)

CubeU20CV10 <- objectsPositionU20CV10[objectsPositionU20CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U20CV10_check_Cube <- tail(CubeU20CV10, n = 1)

CylinderU20CV10 <- objectsPositionU20CV10[objectsPositionU20CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U20CV10_check_Cylinder <- tail(CylinderU20CV10, n = 1)

EggU20CV10 <- objectsPositionU20CV10[objectsPositionU20CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U20CV10_check_Egg <- tail(EggU20CV10, n = 1)

Capsule2U20CV10 <- objectsPositionU20CV10[objectsPositionU20CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U20CV10_check_Capsule2 <- tail(Capsule2U20CV10, n = 1)

Cylinder2U20CV10 <- objectsPositionU20CV10[objectsPositionU20CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U20CV10_check_Cylinder2 <- tail(Cylinder2U20CV10, n = 1)

SphereU20CV10 <- objectsPositionU20CV10[objectsPositionU20CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U20CV10_check_Sphere <- tail(SphereU20CV10, n = 1)

Cylinder_3U20CV10 <- objectsPositionU20CV10[objectsPositionU20CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U20CV10_check_Cylinder_3 <- tail(Cylinder_3U20CV10, n = 1)

U20CV10_check_total <- rbind(U20CV10_check_Cube2, U20CV10_check_Capsule, U20CV10_check_Cube_1,
                             U20CV10_check_Cube, U20CV10_check_Cylinder, U20CV10_check_Egg, 
                             U20CV10_check_Capsule2, U20CV10_check_Cylinder2, U20CV10_check_Sphere, 
                             U20CV10_check_Cylinder_3)
write.xlsx(objectsPositionU20CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU20CV10", append=TRUE)
write.xlsx(U20CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U20CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U21CV10 -------------------
## copio dati da JSON
U21CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_15_05_13_U21.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU21CV10<-U21CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU21CV10<-U21CV10[[2]][[1]]
objectsPositionU21CV10$Utente <- "U21CV"

## creo tabella per ogni oggetto
Cube2U21CV10 <- objectsPositionU21CV10[objectsPositionU21CV10$objPosition %like% "Cube2", ]
Cube2U21CV10$Utente <- "U21CV"
## controllo ultima posizione
U21CV10_check_Cube2 <- tail(Cube2U21CV10, n = 1)

CapsuleU21CV10 <- objectsPositionU21CV10[objectsPositionU21CV10$objPosition %like% "Capsule", ]
CapsuleU21CV10$Utente <- "U21CV"
## controllo ultima posizione
U21CV10_check_Capsule <- tail(CapsuleU21CV10, n = 1)

Cube_1U21CV10 <- objectsPositionU21CV10[objectsPositionU21CV10$objPosition %like% "Cube 1", ]
Cube_1U21CV10$Utente <- "U21CV"
## controllo ultima posizione
U21CV10_check_Cube_1 <- tail(Cube_1U21CV10, n = 1)

CubeU21CV10 <- objectsPositionU21CV10[objectsPositionU21CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U21CV10_check_Cube <- tail(CubeU21CV10, n = 1)

CylinderU21CV10 <- objectsPositionU21CV10[objectsPositionU21CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U21CV10_check_Cylinder <- tail(CylinderU21CV10, n = 1)

EggU21CV10 <- objectsPositionU21CV10[objectsPositionU21CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U21CV10_check_Egg <- tail(EggU21CV10, n = 1)

Capsule2U21CV10 <- objectsPositionU21CV10[objectsPositionU21CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U21CV10_check_Capsule2 <- tail(Capsule2U21CV10, n = 1)

Cylinder2U21CV10 <- objectsPositionU21CV10[objectsPositionU21CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U21CV10_check_Cylinder2 <- tail(Cylinder2U21CV10, n = 1)

SphereU21CV10 <- objectsPositionU21CV10[objectsPositionU21CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U21CV10_check_Sphere <- tail(SphereU21CV10, n = 1)

Cylinder_3U21CV10 <- objectsPositionU21CV10[objectsPositionU21CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U21CV10_check_Cylinder_3 <- tail(Cylinder_3U21CV10, n = 1)

U21CV10_check_total <- rbind(U21CV10_check_Cube2, U21CV10_check_Capsule, U21CV10_check_Cube_1,
                             U21CV10_check_Cube, U21CV10_check_Cylinder, U21CV10_check_Egg, 
                             U21CV10_check_Capsule2, U21CV10_check_Cylinder2, U21CV10_check_Sphere, 
                             U21CV10_check_Cylinder_3)
write.xlsx(objectsPositionU21CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU21CV10", append=TRUE)
write.xlsx(U21CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U21CV10_check_total", append=TRUE)
```

```{r}
## ------------------- U22CV10 -------------------
## copio dati da JSON
U22CV10 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_16_27_26_U22.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU22CV10<-U22CV10[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU22CV10<-U22CV10[[2]][[1]]
objectsPositionU22CV10$Utente <- "U22CV"

## creo tabella per ogni oggetto
Cube2U22CV10 <- objectsPositionU22CV10[objectsPositionU22CV10$objPosition %like% "Cube2", ]
Cube2U22CV10$Utente <- "U22CV"
## controllo ultima posizione
U22CV10_check_Cube2 <- tail(Cube2U22CV10, n = 1)

CapsuleU22CV10 <- objectsPositionU22CV10[objectsPositionU22CV10$objPosition %like% "Capsule", ]
CapsuleU22CV10$Utente <- "U22CV"
## controllo ultima posizione
U22CV10_check_Capsule <- tail(CapsuleU22CV10, n = 1)

Cube_1U22CV10 <- objectsPositionU22CV10[objectsPositionU22CV10$objPosition %like% "Cube 1", ]
Cube_1U22CV10$Utente <- "U22CV"
## controllo ultima posizione
U22CV10_check_Cube_1 <- tail(Cube_1U22CV10, n = 1)

CubeU22CV10 <- objectsPositionU22CV10[objectsPositionU22CV10$objPosition %like% "Cube", ]
## controllo ultima posizione
U22CV10_check_Cube <- tail(CubeU22CV10, n = 1)

CylinderU22CV10 <- objectsPositionU22CV10[objectsPositionU22CV10$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U22CV10_check_Cylinder <- tail(CylinderU22CV10, n = 1)

EggU22CV10 <- objectsPositionU22CV10[objectsPositionU22CV10$objPosition %like% "Egg", ]
## controllo ultima posizione
U22CV10_check_Egg <- tail(EggU22CV10, n = 1)

Capsule2U22CV10 <- objectsPositionU22CV10[objectsPositionU22CV10$objPosition %like% "Capsule2", ]
## controllo ultima posizione
U22CV10_check_Capsule2 <- tail(Capsule2U22CV10, n = 1)

Cylinder2U22CV10 <- objectsPositionU22CV10[objectsPositionU22CV10$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U22CV10_check_Cylinder2 <- tail(Cylinder2U22CV10, n = 1)

SphereU22CV10 <- objectsPositionU22CV10[objectsPositionU22CV10$objPosition %like% "Sphere", ]
## controllo ultima posizione
U22CV10_check_Sphere <- tail(SphereU22CV10, n = 1)

Cylinder_3U22CV10 <- objectsPositionU22CV10[objectsPositionU22CV10$objPosition %like% "Cylinder_3", ]
## controllo ultima posizione
U22CV10_check_Cylinder_3 <- tail(Cylinder_3U22CV10, n = 1)

U22CV10_check_total <- rbind(U22CV10_check_Cube2, U22CV10_check_Capsule, U22CV10_check_Cube_1,
                             U22CV10_check_Cube, U22CV10_check_Cylinder, U22CV10_check_Egg, 
                             U22CV10_check_Capsule2, U22CV10_check_Cylinder2, U22CV10_check_Sphere, 
                             U22CV10_check_Cylinder_3)
write.xlsx(objectsPositionU22CV10, file = "objectsPositionCV10.xlsx", sheetName="objectsPositionU22CV10", append=TRUE)
write.xlsx(U22CV10_check_total, file = "objectsPositionCV10.xlsx", sheetName="U22CV10_check_total", append=TRUE)
```