---
title: "CV3_HMS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# librerie
library("jsonlite")
library("dplyr")
library("tidyr")
library("tidyverse")
library("data.table")
library("xlsx")
library("readxl")
library("gapminder")
library("convertr")
library("zoo")
library("magrittr") 
```

```{r}
## ------------------- U01CV3 -------------------
## copio dati da JSON
U01CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_03_13_59_40_U01.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU01CV3<-U01CV3[[1]][[1]]

## creo tabella contenente i movimenti degli oggetti
objectsPositionU01CV3<-U01CV3[[2]][[1]]
View(objectsPositionU01CV3)
objectsPositionU01CV3$Utente <- "U01CV" # aggiungo colonna con nome utente

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU01CV3 <- objectsPositionU01CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU01CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU01CV3.csv", row.names = FALSE)

# copio e incollo in "U01CV" modifico a mano, mettendo su una riga e sostituisco / con :

# U01CV.csv contiene nome, inizio, fine
U01CV <- read.csv("U01CV.csv", encoding = "UTF-8")
View(U01CV)

## creo tabella per ogni oggetto
cylinderU01CV3 <- objectsPositionU01CV3[objectsPositionU01CV3$objPosition %like% "Cylinder", ]
cylinderU01CV3$Utente <- "U01CV"
## controllo ultima posizione
U01CV3_check_cylinder <- tail(cylinderU01CV3, n = 1)

cubeU01CV3 <- objectsPositionU01CV3[objectsPositionU01CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U01CV3_check_cube <- tail(cubeU01CV3, n = 1)

sphereU01CV3 <- objectsPositionU01CV3[objectsPositionU01CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U01CV3_check_sphere <- tail(sphereU01CV3, n = 1)

U01CV3_check_total <- rbind(U01CV3_check_cylinder, U01CV3_check_cube, U01CV3_check_sphere)

# magie sulla tab
objPosU01CV <- U01CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU01CV) <- c("Utente", "Cube", "Cylinder", "Sphere")

# unisco U01CV.csv creato prima con objPosU01CV
U01CV3_final <- inner_join(objPosU01CV, U01CV, by="Utente")
U01CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U01CV3_final, file = "CV3_final.xlsx", sheetName="U01CV3_final", append=TRUE)
```

```{r}
## ------------------- U02CV3 -------------------
## copio dati da JSON
U02CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_03_15_29_10_U02.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU02CV3<-U02CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU02CV3<-U02CV3[[2]][[1]]
objectsPositionU02CV3$Utente <- "U02CV"

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU02CV3 <- objectsPositionU02CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU02CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU02CV3.csv", row.names = FALSE)

# copio e incollo in "U02CV.csv" modifico a mano, mettendo su una riga e sostituisco / con :

# U02CV.csv contiene nome, inizio, fine
U02CV <- read.csv("U02CV.csv", encoding = "UTF-8")
View(U02CV)

## creo tabella per ogni oggetto
cylinderU02CV3 <- objectsPositionU02CV3[objectsPositionU02CV3$objPosition %like% "Cylinder", ]
cylinderU02CV3$Utente <- "U02CV"
## controllo ultima posizione
U02CV3_check_cylinder <- tail(cylinderU02CV3, n = 1)

cubeU02CV3 <- objectsPositionU02CV3[objectsPositionU02CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U02CV3_check_cube <- tail(cubeU02CV3, n = 1)

sphereU02CV3 <- objectsPositionU02CV3[objectsPositionU02CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U02CV3_check_sphere <- tail(sphereU02CV3, n = 1)

U02CV3_check_total <- rbind(U02CV3_check_cylinder, U02CV3_check_cube, U02CV3_check_sphere)

# magie sulla tab
objPosU02CV <- U02CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU02CV) <- c("Utente", "Cube", "Cylinder", "Sphere")

# unisco U02CV.csv creato prima con objPosU02CV
U02CV3_final <- inner_join(objPosU02CV, U02CV, by="Utente")
U02CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U02CV3_final, file = "CV3_final.xlsx", sheetName="U02CV3_final", append=TRUE)
```

```{r}
## ------------------- U03CV3 -------------------
## copio dati da JSON
U03CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_03_16_04_50_U03.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU03CV3<-U03CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU03CV3<-U03CV3[[2]][[1]]
objectsPositionU03CV3$Utente <- "U03CV"

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU03CV3 <- objectsPositionU03CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU03CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU03CV3.csv", row.names = FALSE)

# copio e incollo in "U03CV" modifico a mano, mettendo su una riga e sostituisco / con :


# U03CV.csv contiene nome, inizio, fine
U03CV <- read.csv("U03CV.csv", encoding = "UTF-8")
View(U03CV)

## creo tabella per ogni oggetto
cylinderU03CV3 <- objectsPositionU03CV3[objectsPositionU03CV3$objPosition %like% "Cylinder", ]
cylinderU03CV3$Utente <- "U03CV"
## controllo ultima posizione
U03CV3_check_cylinder <- tail(cylinderU03CV3, n = 1)

cubeU03CV3 <- objectsPositionU03CV3[objectsPositionU03CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U03CV3_check_cube <- tail(cubeU03CV3, n = 1)

sphereU03CV3 <- objectsPositionU03CV3[objectsPositionU03CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U03CV3_check_sphere <- tail(sphereU03CV3, n = 1)

U03CV3_check_total <- rbind(U03CV3_check_cylinder, U03CV3_check_cube, U03CV3_check_sphere)

# magie sulla tab
objPosU03CV <- U03CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU03CV) <- c("Utente", "Cube", "Cylinder", "Sphere")
```

```{r}
# unisco U03CV.csv creato prima con objPosU03CV
U03CV3_final <- inner_join(objPosU03CV, U03CV, by="Utente")
U03CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U03CV3_final, file = "CV3_final.xlsx", sheetName="U03CV32_final", append=TRUE)

```


```{r}
## ------------------- U04CV3 -------------------
## copio dati da JSON
U04CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_09_33_26_U04.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU04CV3<-U04CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU04CV3<-U04CV3[[2]][[1]]
objectsPositionU04CV3$Utente <- "U04CV"

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU04CV3 <- objectsPositionU04CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU04CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU04CV3.csv", row.names = FALSE)

# copio e incollo "inizioFineU04CV3.csv" in "U04CV" modifico a mano, mettendo su una riga e sostituisco / con :

```

```{r}
# copio e incollo in "U04CV.csv" modifico a mano, mettendo su una riga e sostituisco / con :
# U04CV.csv contiene nome, inizio, fine
U04CV <- read.csv("U04CV.csv", encoding = "UTF-8")
View(U04CV)

## creo tabella per ogni oggetto
cylinderU04CV3 <- objectsPositionU04CV3[objectsPositionU04CV3$objPosition %like% "Cylinder", ]
cylinderU04CV3$Utente <- "U04CV"
## controllo ultima posizione
U04CV3_check_cylinder <- tail(cylinderU04CV3, n = 1)

cubeU04CV3 <- objectsPositionU04CV3[objectsPositionU04CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U04CV3_check_cube <- tail(cubeU04CV3, n = 1)

sphereU04CV3 <- objectsPositionU04CV3[objectsPositionU04CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U04CV3_check_sphere <- tail(sphereU04CV3, n = 1)

U04CV3_check_total <- rbind(U04CV3_check_cylinder, U04CV3_check_cube, U04CV3_check_sphere)

# magie sulla tab
objPosU04CV <- U04CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU04CV) <- c("Utente", "Cube", "Cylinder", "Sphere")
```

```{r}
# unisco U04CV.csv creato prima con objPosU04CV
U04CV3_final <- inner_join(objPosU04CV, U04CV, by="Utente")
U04CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U04CV3_final, file = "CV3_final.xlsx", sheetName="U04CV3_final", append=TRUE)

```

```{r}
## ------------------- U05CV3 -------------------
## copio dati da JSON
U05CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_10_32_15_U05.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU05CV3<-U05CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU05CV3<-U05CV3[[2]][[1]]
objectsPositionU05CV3$Utente <- "U05CV"

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU05CV3 <- objectsPositionU05CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU05CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU05CV3.csv", row.names = FALSE)
```

```{r}
# copio e incollo in "U05CV.csv" modifico a mano, mettendo su una riga e sostituisco / con :
# U05CV.csv contiene nome, inizio, fine
U05CV <- read.csv("U05CV.csv", encoding = "UTF-8")
View(U05CV)

## creo tabella per ogni oggetto
cylinderU05CV3 <- objectsPositionU05CV3[objectsPositionU05CV3$objPosition %like% "Cylinder", ]
cylinderU05CV3$Utente <- "U05CV"
## controllo ultima posizione
U05CV3_check_cylinder <- tail(cylinderU05CV3, n = 1)

cubeU05CV3 <- objectsPositionU05CV3[objectsPositionU05CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U05CV3_check_cube <- tail(cubeU05CV3, n = 1)

sphereU05CV3 <- objectsPositionU05CV3[objectsPositionU05CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U05CV3_check_sphere <- tail(sphereU05CV3, n = 1)

U05CV3_check_total <- rbind(U05CV3_check_cylinder, U05CV3_check_cube, U05CV3_check_sphere)

# magie sulla tab
objPosU05CV <- U05CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU05CV) <- c("Utente", "Cube", "Cylinder", "Sphere")
```

```{r}
# unisco U05CV.csv creato prima con objPosU05CV
U05CV3_final <- inner_join(objPosU05CV, U05CV, by="Utente")
U05CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U05CV3_final, file = "CV3_final.xlsx", sheetName="U05CV3_final", append=TRUE)

```

```{r}
## ------------------- U06CV3 -------------------
## copio dati da JSON
U06CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_11_31_59_U06.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU06CV3<-U06CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU06CV3<-U06CV3[[2]][[1]]
objectsPositionU06CV3$Utente <- "U06CV"

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU06CV3 <- objectsPositionU06CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU06CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU06CV3.csv", row.names = FALSE)
```

```{r}
# copio e incollo in "U06CV.csv" modifico a mano, mettendo su una riga e sostituisco / con :
# U06CV.csv contiene nome, inizio, fine
U06CV <- read.csv("U06CV.csv", encoding = "UTF-8")
View(U06CV)

## creo tabella per ogni oggetto
cylinderU06CV3 <- objectsPositionU06CV3[objectsPositionU06CV3$objPosition %like% "Cylinder", ]
cylinderU06CV3$Utente <- "U06CV"
## controllo ultima posizione
U06CV3_check_cylinder <- tail(cylinderU06CV3, n = 1)

cubeU06CV3 <- objectsPositionU06CV3[objectsPositionU06CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U06CV3_check_cube <- tail(cubeU06CV3, n = 1)

sphereU06CV3 <- objectsPositionU06CV3[objectsPositionU06CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U06CV3_check_sphere <- tail(sphereU06CV3, n = 1)

U06CV3_check_total <- rbind(U06CV3_check_cylinder, U06CV3_check_cube, U06CV3_check_sphere)

# magie sulla tab
objPosU06CV <- U06CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU06CV) <- c("Utente", "Cube", "Cylinder", "Sphere")
```

```{r}
# unisco U06CV.csv creato prima con objPosU06CV
U06CV3_final <- inner_join(objPosU06CV, U06CV, by="Utente")
U06CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U06CV3_final, file = "CV3_final.xlsx", sheetName="U06CV3_final", append=TRUE)

```

```{r}
## ------------------- U07CV3 -------------------
## copio dati da JSON
U07CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_14_15_38_U07.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU07CV3<-U07CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU07CV3<-U07CV3[[2]][[1]]
objectsPositionU07CV3$Utente <- "U07CV"

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU07CV3 <- objectsPositionU07CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU07CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU07CV3.csv", row.names = FALSE)
```

```{r}
# copio e incollo in "U07CV.csv" modifico a mano, mettendo su una riga e sostituisco / con :
# U07CV.csv contiene nome, inizio, fine
U07CV <- read.csv("U07CV.csv", encoding = "UTF-8")
View(U07CV)

## creo tabella per ogni oggetto
cylinderU07CV3 <- objectsPositionU07CV3[objectsPositionU07CV3$objPosition %like% "Cylinder", ]
cylinderU07CV3$Utente <- "U07CV"
## controllo ultima posizione
U07CV3_check_cylinder <- tail(cylinderU07CV3, n = 1)

cubeU07CV3 <- objectsPositionU07CV3[objectsPositionU07CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U07CV3_check_cube <- tail(cubeU07CV3, n = 1)

sphereU07CV3 <- objectsPositionU07CV3[objectsPositionU07CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U07CV3_check_sphere <- tail(sphereU07CV3, n = 1)

U07CV3_check_total <- rbind(U07CV3_check_cylinder, U07CV3_check_cube, U07CV3_check_sphere)

# magie sulla tab
objPosU07CV <- U07CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU07CV) <- c("Utente", "Cube", "Cylinder", "Sphere")
```

```{r}
# unisco U07CV.csv creato prima con objPosU07CV
U07CV3_final <- inner_join(objPosU07CV, U07CV, by="Utente")
U07CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U07CV3_final, file = "CV3_final.xlsx", sheetName="U07CV3_final", append=TRUE)

```

```{r}
## ------------------- U08CV3 -------------------
## copio dati da JSON
U08CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_15_39_57_U08.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU08CV3<-U08CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU08CV3<-U08CV3[[2]][[1]]
objectsPositionU08CV3$Utente <- "U08CV"

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU08CV3 <- objectsPositionU08CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU08CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU08CV3.csv", row.names = FALSE)
```

```{r}
# copio e incollo in "U08CV.csv" modifico a mano, mettendo su una riga e sostituisco / con :
# U08CV.csv contiene nome, inizio, fine
U08CV <- read.csv("U08CV.csv", encoding = "UTF-8")
View(U08CV)

## creo tabella per ogni oggetto
cylinderU08CV3 <- objectsPositionU08CV3[objectsPositionU08CV3$objPosition %like% "Cylinder", ]
cylinderU08CV3$Utente <- "U08CV"
## controllo ultima posizione
U08CV3_check_cylinder <- tail(cylinderU08CV3, n = 1)

cubeU08CV3 <- objectsPositionU08CV3[objectsPositionU08CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U08CV3_check_cube <- tail(cubeU08CV3, n = 1)

sphereU08CV3 <- objectsPositionU08CV3[objectsPositionU08CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U08CV3_check_sphere <- tail(sphereU08CV3, n = 1)

U08CV3_check_total <- rbind(U08CV3_check_cylinder, U08CV3_check_cube, U08CV3_check_sphere)

# magie sulla tab
objPosU08CV <- U08CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU08CV) <- c("Utente", "Cube", "Cylinder", "Sphere")
```

```{r}
# unisco U08CV.csv creato prima con objPosU08CV
U08CV3_final <- inner_join(objPosU08CV, U08CV, by="Utente")
U08CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U08CV3_final, file = "CV3_final.xlsx", sheetName="U08CV3_final", append=TRUE)

```

```{r}
## ------------------- U09CV3 -------------------
## copio dati da JSON
U09CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_04_16_22_58_U09.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU09CV3<-U09CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU09CV3<-U09CV3[[2]][[1]]
objectsPositionU09CV3$Utente <- "U09CV"

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU09CV3 <- objectsPositionU09CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU09CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU09CV3.csv", row.names = FALSE)
```

```{r}
# copio e incollo in "U09CV.csv" modifico a mano, mettendo su una riga e sostituisco / con :
# U09CV.csv contiene nome, inizio, fine
U09CV <- read.csv("U09CV.csv", encoding = "UTF-8")
View(U09CV)

## creo tabella per ogni oggetto
cylinderU09CV3 <- objectsPositionU09CV3[objectsPositionU09CV3$objPosition %like% "Cylinder", ]
cylinderU09CV3$Utente <- "U09CV"
## controllo ultima posizione
U09CV3_check_cylinder <- tail(cylinderU09CV3, n = 1)

cubeU09CV3 <- objectsPositionU09CV3[objectsPositionU09CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U09CV3_check_cube <- tail(cubeU09CV3, n = 1)

sphereU09CV3 <- objectsPositionU09CV3[objectsPositionU09CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U09CV3_check_sphere <- tail(sphereU09CV3, n = 1)

U09CV3_check_total <- rbind(U09CV3_check_cylinder, U09CV3_check_cube, U09CV3_check_sphere)

# magie sulla tab
objPosU09CV <- U09CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU09CV) <- c("Utente", "Cube", "Cylinder", "Sphere")
```

```{r}
# unisco U09CV.csv creato prima con objPosU09CV
U09CV3_final <- inner_join(objPosU09CV, U09CV, by="Utente")
U09CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U09CV3_final, file = "CV3_final.xlsx", sheetName="U09CV3_final", append=TRUE)

```

```{r}
## ------------------- U10CV3 -------------------
## copio dati da JSON
U10CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_05_09_51_39_U10.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU10CV3<-U10CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU10CV3<-U10CV3[[2]][[1]]
objectsPositionU10CV3$Utente <- "U10CV"

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU10CV3 <- objectsPositionU10CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU10CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU10CV3.csv", row.names = FALSE)
```

```{r}
# copio e incollo in "U10CV.csv" modifico a mano, mettendo su una riga e sostituisco / con :
# U10CV.csv contiene nome, inizio, fine
U10CV <- read.csv("U10CV.csv", encoding = "UTF-8")
View(U10CV)

## creo tabella per ogni oggetto
cylinderU10CV3 <- objectsPositionU10CV3[objectsPositionU10CV3$objPosition %like% "Cylinder", ]
cylinderU10CV3$Utente <- "U10CV"
## controllo ultima posizione
U10CV3_check_cylinder <- tail(cylinderU10CV3, n = 1)

cubeU10CV3 <- objectsPositionU10CV3[objectsPositionU10CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U10CV3_check_cube <- tail(cubeU10CV3, n = 1)

sphereU10CV3 <- objectsPositionU10CV3[objectsPositionU10CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U10CV3_check_sphere <- tail(sphereU10CV3, n = 1)

U10CV3_check_total <- rbind(U10CV3_check_cylinder, U10CV3_check_cube, U10CV3_check_sphere)

# magie sulla tab
objPosU10CV <- U10CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU10CV) <- c("Utente", "Cube", "Cylinder", "Sphere")
```

```{r}
# unisco U10CV.csv creato prima con objPosU10CV
U10CV3_final <- inner_join(objPosU10CV, U10CV, by="Utente")
U10CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U10CV3_final, file = "CV3_final.xlsx", sheetName="U10CV3_final", append=TRUE)

```

```{r}
## ------------------- U11CV3 -------------------
## copio dati da JSON
U11CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_05_10_59_30_U11.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU11CV3<-U11CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU11CV3<-U11CV3[[2]][[1]]
objectsPositionU11CV3$Utente <- "U11CV"

## tabella primo e ultimo movimento per calcolare inizio e fine (1)
inizioFineU11CV3 <- objectsPositionU11CV3 %>%
  group_by(Utente) %>%
  slice(c(1, n())) %>%
  ungroup() %>%
  select(Utente, timestamp)  # fin qua funziona tutto

# creo file con primo e ultimo movimento
write.csv(inizioFineU11CV3, "C:/Users/Edoardo/Documents/HapticMemorySequence/inizioFineU11CV3.csv", row.names = FALSE)
```

```{r}
# copio e incollo in "U11CV.csv" modifico a mano, mettendo su una riga e sostituisco / con :
# U11CV.csv contiene nome, inizio, fine
U11CV <- read.csv("U11CV.csv", encoding = "UTF-8")
View(U11CV)

## creo tabella per ogni oggetto
cylinderU11CV3 <- objectsPositionU11CV3[objectsPositionU11CV3$objPosition %like% "Cylinder", ]
cylinderU11CV3$Utente <- "U11CV"
## controllo ultima posizione
U11CV3_check_cylinder <- tail(cylinderU11CV3, n = 1)

cubeU11CV3 <- objectsPositionU11CV3[objectsPositionU11CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U11CV3_check_cube <- tail(cubeU11CV3, n = 1)

sphereU11CV3 <- objectsPositionU11CV3[objectsPositionU11CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U11CV3_check_sphere <- tail(sphereU11CV3, n = 1)

U11CV3_check_total <- rbind(U11CV3_check_cylinder, U11CV3_check_cube, U11CV3_check_sphere)

# magie sulla tab
objPosU11CV <- U11CV3_check_total %>%
  separate(objPosition, into = c("object", "position"), sep = " ", convert =  TRUE) %>%
    spread(key = object, value = position) %>%
  select(Utente, 'Cube(Clone)', 'Cylinder(Clone)', 'Sphere(Clone)') %>%
  group_by(Utente) %>%
    mutate_all(funs(na.locf(., na.rm = FALSE, fromLast = FALSE))) %>%filter(row_number()==n())

colnames(objPosU11CV) <- c("Utente", "Cube", "Cylinder", "Sphere")
```

```{r}
# unisco U11CV.csv creato prima con objPosU11CV
U11CV3_final <- inner_join(objPosU11CV, U11CV, by="Utente")
U11CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U11CV3_final, file = "CV3_final.xlsx", sheetName="U11CV3_final", append=TRUE)

```

```{r}
## ------------------- U12CV3 -------------------
## copio dati da JSON
U12CV3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_05_11_51_58_U12.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU12CV3<-U12CV3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU12CV3<-U12CV3[[2]][[1]]
objectsPositionU12CV3$Utente <- "U12CV"

# copio e incollo in "U12CV.csv" modifico a mano, mettendo su una riga e sostituisco / con :
# U12CV.csv contiene nome, inizio, fine
U12CV <- read.csv("U12CV.csv", encoding = "UTF-8")
View(U12CV)

## creo tabella per ogni oggetto
cylinderU12CV3 <- objectsPositionU12CV3[objectsPositionU12CV3$objPosition %like% "Cylinder", ]
cylinderU12CV3$Utente <- "U12CV"
## controllo ultima posizione
U12CV3_check_cylinder <- tail(cylinderU12CV3, n = 1)

cubeU12CV3 <- objectsPositionU12CV3[objectsPositionU12CV3$objPosition %like% "Cube", ]
## controllo ultima posizione
U12CV3_check_cube <- tail(cubeU12CV3, n = 1)

sphereU12CV3 <- objectsPositionU12CV3[objectsPositionU12CV3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U12CV3_check_sphere <- tail(sphereU12CV3, n = 1)

U12CV3_check_total <- rbind(U12CV3_check_cylinder, U12CV3_check_cube, U12CV3_check_sphere)

```

```{r}
# unisco U12CV.csv creato prima con objPosU12CV
U12CV3_final <- inner_join(objPosU12CV, U12CV, by="Utente")
U12CV3_final %>%
  select(Utente, Inizio, Fine, Cube, Cylinder, Sphere)

# scrivo il file xlsx
write.xlsx(U12CV3_final, file = "CV3_final.xlsx", sheetName="U12CV3_final", append=TRUE)

```

```{r}
## ------------------- tabella con risutltati di tutti gli utenti -------------------
objPosAllUsers <- rbind(objPosU01CV, objPosU02CV, objPosU03CV, 
                        objPosU04CV, objPosU05CV, objPosU06CV, 
                        objPosU07CV, objPosU08CV, objPosU09CV, 
                        objPosU10CV, objPosU11CV, objPosU12CV)

View(objPosAllUsers)


## ------------------- tabella con tutti gli utenti -------------------
CV3_allUsers <- rbind(U01CV3_check_total, U02CV3_check_total, U03CV3_check_total,
             U04CV3_check_total, U05CV3_check_total, U06CV3_check_total,
             U07CV3_check_total, U08CV3_check_total, U09CV3_check_total,
             U10CV3_check_total, U11CV3_check_total, U12CV3_check_total)

View(CV3_allUsers)

# Creo colonna "pos"
CV3_allUsers %>%
  select(Utente, objPosition) %>%
  mutate(Pos = case_when(
    endsWith(objPosition, "true") ~ 1,
    endsWith(objPosition, "false") ~ 0
  ))

write.xlsx(CV3_allUsers, file = "CV3_allUsers.xlsx",
           sheetName="CV3_allUsers", append=TRUE)
```

```{r}
## ------------------- U13cv3 -------------------
## copio dati da JSON
U13cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_08_10_55_35_U13.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU13cv3<-U13cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU13cv3<-U13cv3[[2]][[1]]
objectsPositionU13cv3$Utente <- "U13CV"

CylinderU13cv3 <- objectsPositionU13cv3[objectsPositionU13cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U13cv3_check_Cylinder <- tail(CylinderU13cv3, n = 1)

CubeU13cv3 <- objectsPositionU13cv3[objectsPositionU13cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U13cv3_check_Cube <- tail(CubeU13cv3, n = 1)

SphereU13cv3 <- objectsPositionU13cv3[objectsPositionU13cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U13cv3_check_Sphere <- tail(SphereU13cv3, n = 1)

U13cv3_check_total <- rbind(U13cv3_check_Cylinder,U13cv3_check_Cube, U13cv3_check_Sphere)

write.xlsx(U13cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U13cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU13cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU13cv3", append=TRUE)
```

```{r}
## ------------------- U14cv3 -------------------
## copio dati da JSON
U14cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_08_11_47_15_U14.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU14cv3<-U14cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU14cv3<-U14cv3[[2]][[1]]
objectsPositionU14cv3$Utente <- "U14CV"

CylinderU14cv3 <- objectsPositionU14cv3[objectsPositionU14cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U14cv3_check_Cylinder <- tail(CylinderU14cv3, n = 1)

CubeU14cv3 <- objectsPositionU14cv3[objectsPositionU14cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U14cv3_check_Cube <- tail(CubeU14cv3, n = 1)

SphereU14cv3 <- objectsPositionU14cv3[objectsPositionU14cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U14cv3_check_Sphere <- tail(SphereU14cv3, n = 1)

U14cv3_check_total <- rbind(U14cv3_check_Cylinder,U14cv3_check_Cube, U14cv3_check_Sphere)

write.xlsx(U14cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U14cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU14cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU14cv3", append=TRUE)
```

```{r}
## ------------------- U15cv3 -------------------
## copio dati da JSON
U15cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_08_15_18_11_U15.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU15cv3<-U15cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU15cv3<-U15cv3[[2]][[1]]
objectsPositionU15cv3$Utente <- "U15CV"

CylinderU15cv3 <- objectsPositionU15cv3[objectsPositionU15cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U15cv3_check_Cylinder <- tail(CylinderU15cv3, n = 1)

CubeU15cv3 <- objectsPositionU15cv3[objectsPositionU15cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U15cv3_check_Cube <- tail(CubeU15cv3, n = 1)

SphereU15cv3 <- objectsPositionU15cv3[objectsPositionU15cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U15cv3_check_Sphere <- tail(SphereU15cv3, n = 1)

U15cv3_check_total <- rbind(U15cv3_check_Cylinder,U15cv3_check_Cube, U15cv3_check_Sphere)

write.xlsx(U15cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U15cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU15cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU15cv3", append=TRUE)
```

```{r}
## ------------------- U16cv3 -------------------
## copio dati da JSON
U16cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_08_16_30_37_U16.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU16cv3<-U16cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU16cv3<-U16cv3[[2]][[1]]
objectsPositionU16cv3$Utente <- "U16CV"

CylinderU16cv3 <- objectsPositionU16cv3[objectsPositionU16cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U16cv3_check_Cylinder <- tail(CylinderU16cv3, n = 1)

CubeU16cv3 <- objectsPositionU16cv3[objectsPositionU16cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U16cv3_check_Cube <- tail(CubeU16cv3, n = 1)

SphereU16cv3 <- objectsPositionU16cv3[objectsPositionU16cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U16cv3_check_Sphere <- tail(SphereU16cv3, n = 1)

U16cv3_check_total <- rbind(U16cv3_check_Cylinder,U16cv3_check_Cube, U16cv3_check_Sphere)

write.xlsx(U16cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U16cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU16cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU16cv3", append=TRUE)
```

```{r}
## ------------------- U17cv3 -------------------
## copio dati da JSON
U17cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_09_34_39_U17.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU17cv3<-U17cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU17cv3<-U17cv3[[2]][[1]]
objectsPositionU17cv3$Utente <- "U17CV"

CylinderU17cv3 <- objectsPositionU17cv3[objectsPositionU17cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U17cv3_check_Cylinder <- tail(CylinderU17cv3, n = 1)

CubeU17cv3 <- objectsPositionU17cv3[objectsPositionU17cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U17cv3_check_Cube <- tail(CubeU17cv3, n = 1)

SphereU17cv3 <- objectsPositionU17cv3[objectsPositionU17cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U17cv3_check_Sphere <- tail(SphereU17cv3, n = 1)

U17cv3_check_total <- rbind(U17cv3_check_Cylinder,U17cv3_check_Cube, U17cv3_check_Sphere)

write.xlsx(U17cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U17cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU17cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU17cv3", append=TRUE)
```

```{r}
## ------------------- U18cv3 -------------------
## copio dati da JSON
U18cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_10_55_18_U18.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU18cv3<-U18cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU18cv3<-U18cv3[[2]][[1]]
objectsPositionU18cv3$Utente <- "U18CV"

CylinderU18cv3 <- objectsPositionU18cv3[objectsPositionU18cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U18cv3_check_Cylinder <- tail(CylinderU18cv3, n = 1)

CubeU18cv3 <- objectsPositionU18cv3[objectsPositionU18cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U18cv3_check_Cube <- tail(CubeU18cv3, n = 1)

SphereU18cv3 <- objectsPositionU18cv3[objectsPositionU18cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U18cv3_check_Sphere <- tail(SphereU18cv3, n = 1)

U18cv3_check_total <- rbind(U18cv3_check_Cylinder,U18cv3_check_Cube, U18cv3_check_Sphere)

write.xlsx(U18cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U18cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU18cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU18cv3", append=TRUE)
```

```{r}
## ------------------- U19cv3 -------------------
## copio dati da JSON
U19cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_11_39_08_U19.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU19cv3<-U19cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU19cv3<-U19cv3[[2]][[1]]
objectsPositionU19cv3$Utente <- "U19CV"

CylinderU19cv3 <- objectsPositionU19cv3[objectsPositionU19cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U19cv3_check_Cylinder <- tail(CylinderU19cv3, n = 1)

CubeU19cv3 <- objectsPositionU19cv3[objectsPositionU19cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U19cv3_check_Cube <- tail(CubeU19cv3, n = 1)

SphereU19cv3 <- objectsPositionU19cv3[objectsPositionU19cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U19cv3_check_Sphere <- tail(SphereU19cv3, n = 1)

U19cv3_check_total <- rbind(U19cv3_check_Cylinder,U19cv3_check_Cube, U19cv3_check_Sphere)

write.xlsx(U19cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U19cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU19cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU19cv3", append=TRUE)
```

```{r}
## ------------------- U20cv3 -------------------
## copio dati da JSON
U20cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_14_19_52_U20.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU20cv3<-U20cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU20cv3<-U20cv3[[2]][[1]]
objectsPositionU20cv3$Utente <- "U20CV"

CylinderU20cv3 <- objectsPositionU20cv3[objectsPositionU20cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U20cv3_check_Cylinder <- tail(CylinderU20cv3, n = 1)

CubeU20cv3 <- objectsPositionU20cv3[objectsPositionU20cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U20cv3_check_Cube <- tail(CubeU20cv3, n = 1)

SphereU20cv3 <- objectsPositionU20cv3[objectsPositionU20cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U20cv3_check_Sphere <- tail(SphereU20cv3, n = 1)

U20cv3_check_total <- rbind(U20cv3_check_Cylinder,U20cv3_check_Cube, U20cv3_check_Sphere)

write.xlsx(U20cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U20cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU20cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU20cv3", append=TRUE)
```

```{r}
## ------------------- U21cv3 -------------------
## copio dati da JSON
U21cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_15_03_21_U21.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU21cv3<-U21cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU21cv3<-U21cv3[[2]][[1]]
objectsPositionU21cv3$Utente <- "U21CV"

CylinderU21cv3 <- objectsPositionU21cv3[objectsPositionU21cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U21cv3_check_Cylinder <- tail(CylinderU21cv3, n = 1)

CubeU21cv3 <- objectsPositionU21cv3[objectsPositionU21cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U21cv3_check_Cube <- tail(CubeU21cv3, n = 1)

SphereU21cv3 <- objectsPositionU21cv3[objectsPositionU21cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U21cv3_check_Sphere <- tail(SphereU21cv3, n = 1)

U21cv3_check_total <- rbind(U21cv3_check_Cylinder,U21cv3_check_Cube, U21cv3_check_Sphere)

write.xlsx(U21cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U21cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU21cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU21cv3", append=TRUE)
```

```{r}
## ------------------- U22cv3 -------------------
## copio dati da JSON
U22cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_09_16_26_20_U22.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU22cv3<-U22cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU22cv3<-U22cv3[[2]][[1]]
objectsPositionU22cv3$Utente <- "U22CV"

CylinderU22cv3 <- objectsPositionU22cv3[objectsPositionU22cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U22cv3_check_Cylinder <- tail(CylinderU22cv3, n = 1)

CubeU22cv3 <- objectsPositionU22cv3[objectsPositionU22cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U22cv3_check_Cube <- tail(CubeU22cv3, n = 1)

SphereU22cv3 <- objectsPositionU22cv3[objectsPositionU22cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U22cv3_check_Sphere <- tail(SphereU22cv3, n = 1)

U22cv3_check_total <- rbind(U22cv3_check_Cylinder,U22cv3_check_Cube, U22cv3_check_Sphere)

write.xlsx(U22cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U22cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU22cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU22cv3", append=TRUE)
```

```{r}
## ------------------- U23cv3 -------------------
## copio dati da JSON
U23cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_10_09_39_43_U23.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU23cv3<-U23cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU23cv3<-U23cv3[[2]][[1]]
objectsPositionU23cv3$Utente <- "U23CV"

CylinderU23cv3 <- objectsPositionU23cv3[objectsPositionU23cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U23cv3_check_Cylinder <- tail(CylinderU23cv3, n = 1)

CubeU23cv3 <- objectsPositionU23cv3[objectsPositionU23cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U23cv3_check_Cube <- tail(CubeU23cv3, n = 1)

SphereU23cv3 <- objectsPositionU23cv3[objectsPositionU23cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U23cv3_check_Sphere <- tail(SphereU23cv3, n = 1)

U23cv3_check_total <- rbind(U23cv3_check_Cylinder,U23cv3_check_Cube, U23cv3_check_Sphere)

write.xlsx(U23cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U23cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU23cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU23cv3", append=TRUE)
```

```{r}
## ------------------- U24cv3 -------------------
## copio dati da JSON
U24cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_10_12_16_50_U24.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU24cv3<-U24cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU24cv3<-U24cv3[[2]][[1]]
objectsPositionU24cv3$Utente <- "U24CV"

CylinderU24cv3 <- objectsPositionU24cv3[objectsPositionU24cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U24cv3_check_Cylinder <- tail(CylinderU24cv3, n = 1)

CubeU24cv3 <- objectsPositionU24cv3[objectsPositionU24cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U24cv3_check_Cube <- tail(CubeU24cv3, n = 1)

SphereU24cv3 <- objectsPositionU24cv3[objectsPositionU24cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U24cv3_check_Sphere <- tail(SphereU24cv3, n = 1)

U24cv3_check_total <- rbind(U24cv3_check_Cylinder,U24cv3_check_Cube, U24cv3_check_Sphere)

write.xlsx(U24cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U24cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU24cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU24cv3", append=TRUE)
```

```{r}
## ------------------- U25cv3 -------------------
## copio dati da JSON
U25cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_10_14_07_11_U25.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU25cv3<-U25cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU25cv3<-U25cv3[[2]][[1]]
objectsPositionU25cv3$Utente <- "U25CV"

CylinderU25cv3 <- objectsPositionU25cv3[objectsPositionU25cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U25cv3_check_Cylinder <- tail(CylinderU25cv3, n = 1)

CubeU25cv3 <- objectsPositionU25cv3[objectsPositionU25cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U25cv3_check_Cube <- tail(CubeU25cv3, n = 1)

SphereU25cv3 <- objectsPositionU25cv3[objectsPositionU25cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U25cv3_check_Sphere <- tail(SphereU25cv3, n = 1)

U25cv3_check_total <- rbind(U25cv3_check_Cylinder,U25cv3_check_Cube, U25cv3_check_Sphere)

write.xlsx(U25cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U25cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU25cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU25cv3", append=TRUE)
```

```{r}
## ------------------- U26cv3 -------------------
## copio dati da JSON
U26cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_10_15_02_55_U26.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU26cv3<-U26cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU26cv3<-U26cv3[[2]][[1]]
objectsPositionU26cv3$Utente <- "U26CV"

CylinderU26cv3 <- objectsPositionU26cv3[objectsPositionU26cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U26cv3_check_Cylinder <- tail(CylinderU26cv3, n = 1)

CubeU26cv3 <- objectsPositionU26cv3[objectsPositionU26cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U26cv3_check_Cube <- tail(CubeU26cv3, n = 1)

SphereU26cv3 <- objectsPositionU26cv3[objectsPositionU26cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U26cv3_check_Sphere <- tail(SphereU26cv3, n = 1)

U26cv3_check_total <- rbind(U26cv3_check_Cylinder,U26cv3_check_Cube, U26cv3_check_Sphere)

write.xlsx(U26cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U26cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU26cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU26cv3", append=TRUE)
```

```{r}
## ------------------- U27cv3 -------------------
## copio dati da JSON
U27cv3 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/CV/HapticMemorySequenceLog_2021_11_10_16_00_45_U27.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU27cv3<-U27cv3[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU27cv3<-U27cv3[[2]][[1]]
objectsPositionU27cv3$Utente <- "U27CV"

CylinderU27cv3 <- objectsPositionU27cv3[objectsPositionU27cv3$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U27cv3_check_Cylinder <- tail(CylinderU27cv3, n = 1)

CubeU27cv3 <- objectsPositionU27cv3[objectsPositionU27cv3$objPosition %like% "Cube", ]
## controllo ultima posizione
U27cv3_check_Cube <- tail(CubeU27cv3, n = 1)

SphereU27cv3 <- objectsPositionU27cv3[objectsPositionU27cv3$objPosition %like% "Sphere", ]
## controllo ultima posizione
U27cv3_check_Sphere <- tail(SphereU27cv3, n = 1)

U27cv3_check_total <- rbind(U27cv3_check_Cylinder,U27cv3_check_Cube, U27cv3_check_Sphere)

write.xlsx(U27cv3_check_total, file = "objectsPositioncv3.xlsx", sheetName="U27cv3_check_total", append=TRUE)
write.xlsx(objectsPositionU27cv3, file = "objectsPositioncv3.xlsx", sheetName="objectsPositionU27cv3", append=TRUE)
```
