---
title: "SG5"
output: html_notebook
---
```{r}
library("jsonlite")
library("dplyr")
library("tidyr")
library("tidyverse")
library("data.table")
library("xlsx")
```

```{r}
## ------------------- U01SG5 -------------------
## copio dati da JSON
U01SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_03_14_14_19_U01.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU01SG5<-U01SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU01SG5<-U01SG5[[2]][[1]]
objectsPositionU01SG5$Utente <- "U01SG"
write.xlsx(objectsPositionU01SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU01SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U01SG5 <- objectsPositionU01SG5[objectsPositionU01SG5$objPosition %like% "Cube2", ]
Cube2U01SG5$Utente <- "U01SG"
## controllo ultima posizione
U01SG5_check_Cube2 <- tail(Cube2U01SG5, n = 1)

CylinderU01SG5 <- objectsPositionU01SG5[objectsPositionU01SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U01SG5_check_Cylinder <- tail(CylinderU01SG5, n = 1)

CubeU01SG5 <- objectsPositionU01SG5[objectsPositionU01SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U01SG5_check_Cube <- tail(CubeU01SG5, n = 1)

Cylinder2U01SG5 <- objectsPositionU01SG5[objectsPositionU01SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U01SG5_check_Cylinder2 <- tail(Cylinder2U01SG5, n = 1)

SphereU01SG5 <- objectsPositionU01SG5[objectsPositionU01SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U01SG5_check_Sphere <- tail(SphereU01SG5, n = 1)

U01SG5_check_total <- rbind(U01SG5_check_Cube2, U01SG5_check_Cylinder,
                            U01SG5_check_Cube, U01SG5_check_Cylinder2,
                            U01SG5_check_Sphere)
write.xlsx(U01SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U01SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U02SG5 -------------------
## copio dati da JSON
U02SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_03_15_13_53_U02.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU02SG5<-U02SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU02SG5<-U02SG5[[2]][[1]]
objectsPositionU02SG5$Utente <- "U02SG"
write.xlsx(objectsPositionU02SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU02SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U02SG5 <- objectsPositionU02SG5[objectsPositionU02SG5$objPosition %like% "Cube2", ]
Cube2U02SG5$Utente <- "U02SG"
## controllo ultima posizione
U02SG5_check_Cube2 <- tail(Cube2U02SG5, n = 1)

CylinderU02SG5 <- objectsPositionU02SG5[objectsPositionU02SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U02SG5_check_Cylinder <- tail(CylinderU02SG5, n = 1)

CubeU02SG5 <- objectsPositionU02SG5[objectsPositionU02SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U02SG5_check_Cube <- tail(CubeU02SG5, n = 1)

Cylinder2U02SG5 <- objectsPositionU02SG5[objectsPositionU02SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U02SG5_check_Cylinder2 <- tail(Cylinder2U02SG5, n = 1)

SphereU02SG5 <- objectsPositionU02SG5[objectsPositionU02SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U02SG5_check_Sphere <- tail(SphereU02SG5, n = 1)

U02SG5_check_total <- rbind(U02SG5_check_Cube2, U02SG5_check_Cylinder,
                            U02SG5_check_Cube, U02SG5_check_Cylinder2,
                            U02SG5_check_Sphere)
write.xlsx(U02SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U02SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U03SG5 -------------------
## copio dati da JSON
U03SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_03_16_19_45_U03.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU03SG5<-U03SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU03SG5<-U03SG5[[2]][[1]]
objectsPositionU03SG5$Utente <- "U03SG"
write.xlsx(objectsPositionU03SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU03SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U03SG5 <- objectsPositionU03SG5[objectsPositionU03SG5$objPosition %like% "Cube2", ]
Cube2U03SG5$Utente <- "U03SG"
## controllo ultima posizione
U03SG5_check_Cube2 <- tail(Cube2U03SG5, n = 1)

CylinderU03SG5 <- objectsPositionU03SG5[objectsPositionU03SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U03SG5_check_Cylinder <- tail(CylinderU03SG5, n = 1)

CubeU03SG5 <- objectsPositionU03SG5[objectsPositionU03SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U03SG5_check_Cube <- tail(CubeU03SG5, n = 1)

Cylinder2U03SG5 <- objectsPositionU03SG5[objectsPositionU03SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U03SG5_check_Cylinder2 <- tail(Cylinder2U03SG5, n = 1)

SphereU03SG5 <- objectsPositionU03SG5[objectsPositionU03SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U03SG5_check_Sphere <- tail(SphereU03SG5, n = 1)

U03SG5_check_total <- rbind(U03SG5_check_Cube2, U03SG5_check_Cylinder,
                            U03SG5_check_Cube, U03SG5_check_Cylinder2,
                            U03SG5_check_Sphere)
write.xlsx(U03SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U03SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U04SG5 -------------------
## copio dati da JSON
U04SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_04_09_51_47_U04.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU04SG5<-U04SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU04SG5<-U04SG5[[2]][[1]]
objectsPositionU04SG5$Utente <- "U04SG"
write.xlsx(objectsPositionU04SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU04SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U04SG5 <- objectsPositionU04SG5[objectsPositionU04SG5$objPosition %like% "Cube2", ]
Cube2U04SG5$Utente <- "U04SG"
## controllo ultima posizione
U04SG5_check_Cube2 <- tail(Cube2U04SG5, n = 1)

CylinderU04SG5 <- objectsPositionU04SG5[objectsPositionU04SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U04SG5_check_Cylinder <- tail(CylinderU04SG5, n = 1)

CubeU04SG5 <- objectsPositionU04SG5[objectsPositionU04SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U04SG5_check_Cube <- tail(CubeU04SG5, n = 1)

Cylinder2U04SG5 <- objectsPositionU04SG5[objectsPositionU04SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U04SG5_check_Cylinder2 <- tail(Cylinder2U04SG5, n = 1)

SphereU04SG5 <- objectsPositionU04SG5[objectsPositionU04SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U04SG5_check_Sphere <- tail(SphereU04SG5, n = 1)

U04SG5_check_total <- rbind(U04SG5_check_Cube2, U04SG5_check_Cylinder,
                            U04SG5_check_Cube, U04SG5_check_Cylinder2,
                            U04SG5_check_Sphere)
write.xlsx(U04SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U04SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U05SG5 -------------------
## copio dati da JSON
U05SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_04_10_45_02_U05.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU05SG5<-U05SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU05SG5<-U05SG5[[2]][[1]]
objectsPositionU05SG5$Utente <- "U05SG"
write.xlsx(objectsPositionU05SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU05SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U05SG5 <- objectsPositionU05SG5[objectsPositionU05SG5$objPosition %like% "Cube2", ]
Cube2U05SG5$Utente <- "U05SG"
## controllo ultima posizione
U05SG5_check_Cube2 <- tail(Cube2U05SG5, n = 1)

CylinderU05SG5 <- objectsPositionU05SG5[objectsPositionU05SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U05SG5_check_Cylinder <- tail(CylinderU05SG5, n = 1)

CubeU05SG5 <- objectsPositionU05SG5[objectsPositionU05SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U05SG5_check_Cube <- tail(CubeU05SG5, n = 1)

Cylinder2U05SG5 <- objectsPositionU05SG5[objectsPositionU05SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U05SG5_check_Cylinder2 <- tail(Cylinder2U05SG5, n = 1)

SphereU05SG5 <- objectsPositionU05SG5[objectsPositionU05SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U05SG5_check_Sphere <- tail(SphereU05SG5, n = 1)

U05SG5_check_total <- rbind(U05SG5_check_Cube2, U05SG5_check_Cylinder,
                            U05SG5_check_Cube, U05SG5_check_Cylinder2,
                            U05SG5_check_Sphere)
write.xlsx(U05SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U05SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U06SG5 -------------------
## copio dati da JSON
U06SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_04_11_21_04_U06.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU06SG5<-U06SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU06SG5<-U06SG5[[2]][[1]]
objectsPositionU06SG5$Utente <- "U06SG"
write.xlsx(objectsPositionU06SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU06SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U06SG5 <- objectsPositionU06SG5[objectsPositionU06SG5$objPosition %like% "Cube2", ]
Cube2U06SG5$Utente <- "U06SG"
## controllo ultima posizione
U06SG5_check_Cube2 <- tail(Cube2U06SG5, n = 1)

CylinderU06SG5 <- objectsPositionU06SG5[objectsPositionU06SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U06SG5_check_Cylinder <- tail(CylinderU06SG5, n = 1)

CubeU06SG5 <- objectsPositionU06SG5[objectsPositionU06SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U06SG5_check_Cube <- tail(CubeU06SG5, n = 1)

Cylinder2U06SG5 <- objectsPositionU06SG5[objectsPositionU06SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U06SG5_check_Cylinder2 <- tail(Cylinder2U06SG5, n = 1)

SphereU06SG5 <- objectsPositionU06SG5[objectsPositionU06SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U06SG5_check_Sphere <- tail(SphereU06SG5, n = 1)

U06SG5_check_total <- rbind(U06SG5_check_Cube2, U06SG5_check_Cylinder,
                            U06SG5_check_Cube, U06SG5_check_Cylinder2,
                            U06SG5_check_Sphere)
write.xlsx(U06SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U06SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U07SG5 -------------------
## copio dati da JSON
U07SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_04_14_32_33_U07.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU07SG5<-U07SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU07SG5<-U07SG5[[2]][[1]]
objectsPositionU07SG5$Utente <- "U07SG"
write.xlsx(objectsPositionU07SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU07SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U07SG5 <- objectsPositionU07SG5[objectsPositionU07SG5$objPosition %like% "Cube2", ]
Cube2U07SG5$Utente <- "U07SG"
## controllo ultima posizione
U07SG5_check_Cube2 <- tail(Cube2U07SG5, n = 1)

CylinderU07SG5 <- objectsPositionU07SG5[objectsPositionU07SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U07SG5_check_Cylinder <- tail(CylinderU07SG5, n = 1)

CubeU07SG5 <- objectsPositionU07SG5[objectsPositionU07SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U07SG5_check_Cube <- tail(CubeU07SG5, n = 1)

Cylinder2U07SG5 <- objectsPositionU07SG5[objectsPositionU07SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U07SG5_check_Cylinder2 <- tail(Cylinder2U07SG5, n = 1)

SphereU07SG5 <- objectsPositionU07SG5[objectsPositionU07SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U07SG5_check_Sphere <- tail(SphereU07SG5, n = 1)

U07SG5_check_total <- rbind(U07SG5_check_Cube2, U07SG5_check_Cylinder,
                            U07SG5_check_Cube, U07SG5_check_Cylinder2,
                            U07SG5_check_Sphere)
write.xlsx(U07SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U07SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U08SG5 -------------------
## copio dati da JSON
U08SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_04_15_25_57_U08.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU08SG5<-U08SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU08SG5<-U08SG5[[2]][[1]]
objectsPositionU08SG5$Utente <- "U08SG"
write.xlsx(objectsPositionU08SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU08SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U08SG5 <- objectsPositionU08SG5[objectsPositionU08SG5$objPosition %like% "Cube2", ]
Cube2U08SG5$Utente <- "U08SG"
## controllo ultima posizione
U08SG5_check_Cube2 <- tail(Cube2U08SG5, n = 1)

CylinderU08SG5 <- objectsPositionU08SG5[objectsPositionU08SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U08SG5_check_Cylinder <- tail(CylinderU08SG5, n = 1)

CubeU08SG5 <- objectsPositionU08SG5[objectsPositionU08SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U08SG5_check_Cube <- tail(CubeU08SG5, n = 1)

Cylinder2U08SG5 <- objectsPositionU08SG5[objectsPositionU08SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U08SG5_check_Cylinder2 <- tail(Cylinder2U08SG5, n = 1)

SphereU08SG5 <- objectsPositionU08SG5[objectsPositionU08SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U08SG5_check_Sphere <- tail(SphereU08SG5, n = 1)

U08SG5_check_total <- rbind(U08SG5_check_Cube2, U08SG5_check_Cylinder,
                            U08SG5_check_Cube, U08SG5_check_Cylinder2,
                            U08SG5_check_Sphere)
write.xlsx(U08SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U08SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U09SG5 -------------------
## copio dati da JSON
U09SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_04_16_37_01_U09.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU09SG5<-U09SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU09SG5<-U09SG5[[2]][[1]]
objectsPositionU09SG5$Utente <- "U09SG"
write.xlsx(objectsPositionU09SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU09SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U09SG5 <- objectsPositionU09SG5[objectsPositionU09SG5$objPosition %like% "Cube2", ]
Cube2U09SG5$Utente <- "U09SG"
## controllo ultima posizione
U09SG5_check_Cube2 <- tail(Cube2U09SG5, n = 1)

CylinderU09SG5 <- objectsPositionU09SG5[objectsPositionU09SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U09SG5_check_Cylinder <- tail(CylinderU09SG5, n = 1)

CubeU09SG5 <- objectsPositionU09SG5[objectsPositionU09SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U09SG5_check_Cube <- tail(CubeU09SG5, n = 1)

Cylinder2U09SG5 <- objectsPositionU09SG5[objectsPositionU09SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U09SG5_check_Cylinder2 <- tail(Cylinder2U09SG5, n = 1)

SphereU09SG5 <- objectsPositionU09SG5[objectsPositionU09SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U09SG5_check_Sphere <- tail(SphereU09SG5, n = 1)

U09SG5_check_total <- rbind(U09SG5_check_Cube2, U09SG5_check_Cylinder,
                            U09SG5_check_Cube, U09SG5_check_Cylinder2,
                            U09SG5_check_Sphere)
write.xlsx(U09SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U09SG5_check_total", append=TRUE)
```


```{r}
## ------------------- U10SG5 -------------------
## copio dati da JSON
U10SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_05_09_39_12_U10.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU10SG5<-U10SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU10SG5<-U10SG5[[2]][[1]]
objectsPositionU10SG5$Utente <- "U10SG"
write.xlsx(objectsPositionU10SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU10SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U10SG5 <- objectsPositionU10SG5[objectsPositionU10SG5$objPosition %like% "Cube2", ]
Cube2U10SG5$Utente <- "U10SG"
## controllo ultima posizione
U10SG5_check_Cube2 <- tail(Cube2U10SG5, n = 1)

CylinderU10SG5 <- objectsPositionU10SG5[objectsPositionU10SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U10SG5_check_Cylinder <- tail(CylinderU10SG5, n = 1)

CubeU10SG5 <- objectsPositionU10SG5[objectsPositionU10SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U10SG5_check_Cube <- tail(CubeU10SG5, n = 1)

Cylinder2U10SG5 <- objectsPositionU10SG5[objectsPositionU10SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U10SG5_check_Cylinder2 <- tail(Cylinder2U10SG5, n = 1)

SphereU10SG5 <- objectsPositionU10SG5[objectsPositionU10SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U10SG5_check_Sphere <- tail(SphereU10SG5, n = 1)

U10SG5_check_total <- rbind(U10SG5_check_Cube2, U10SG5_check_Cylinder,
                            U10SG5_check_Cube, U10SG5_check_Cylinder2,
                            U10SG5_check_Sphere)
write.xlsx(U10SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U10SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U11SG5 -------------------
## copio dati da JSON
U11SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_05_11_13_10_U11.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU11SG5<-U11SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU11SG5<-U11SG5[[2]][[1]]
objectsPositionU11SG5$Utente <- "U11SG"
write.xlsx(objectsPositionU11SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU11SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U11SG5 <- objectsPositionU11SG5[objectsPositionU11SG5$objPosition %like% "Cube2", ]
Cube2U11SG5$Utente <- "U11SG"
## controllo ultima posizione
U11SG5_check_Cube2 <- tail(Cube2U11SG5, n = 1)

CylinderU11SG5 <- objectsPositionU11SG5[objectsPositionU11SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U11SG5_check_Cylinder <- tail(CylinderU11SG5, n = 1)

CubeU11SG5 <- objectsPositionU11SG5[objectsPositionU11SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U11SG5_check_Cube <- tail(CubeU11SG5, n = 1)

Cylinder2U11SG5 <- objectsPositionU11SG5[objectsPositionU11SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U11SG5_check_Cylinder2 <- tail(Cylinder2U11SG5, n = 1)

SphereU11SG5 <- objectsPositionU11SG5[objectsPositionU11SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U11SG5_check_Sphere <- tail(SphereU11SG5, n = 1)

U11SG5_check_total <- rbind(U11SG5_check_Cube2, U11SG5_check_Cylinder,
                            U11SG5_check_Cube, U11SG5_check_Cylinder2,
                            U11SG5_check_Sphere)
write.xlsx(U11SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U11SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U12SG5 -------------------
## copio dati da JSON
U12SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_05_11_39_23_U12.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU12SG5<-U12SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU12SG5<-U12SG5[[2]][[1]]
objectsPositionU12SG5$Utente <- "U12SG"
write.xlsx(objectsPositionU12SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU12SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U12SG5 <- objectsPositionU12SG5[objectsPositionU12SG5$objPosition %like% "Cube2", ]
Cube2U12SG5$Utente <- "U12SG"
## controllo ultima posizione
U12SG5_check_Cube2 <- tail(Cube2U12SG5, n = 1)

CylinderU12SG5 <- objectsPositionU12SG5[objectsPositionU12SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U12SG5_check_Cylinder <- tail(CylinderU12SG5, n = 1)

CubeU12SG5 <- objectsPositionU12SG5[objectsPositionU12SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U12SG5_check_Cube <- tail(CubeU12SG5, n = 1)

Cylinder2U12SG5 <- objectsPositionU12SG5[objectsPositionU12SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U12SG5_check_Cylinder2 <- tail(Cylinder2U12SG5, n = 1)

SphereU12SG5 <- objectsPositionU12SG5[objectsPositionU12SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U12SG5_check_Sphere <- tail(SphereU12SG5, n = 1)

U12SG5_check_total <- rbind(U12SG5_check_Cube2, U12SG5_check_Cylinder,
                            U12SG5_check_Cube, U12SG5_check_Cylinder2,
                            U12SG5_check_Sphere)
write.xlsx(U12SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U12SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U13SG5 -------------------
## copio dati da JSON
U13SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_08_11_10_44_U13.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU13SG5<-U13SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU13SG5<-U13SG5[[2]][[1]]
objectsPositionU13SG5$Utente <- "U13SG"
write.xlsx(objectsPositionU13SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU13SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U13SG5 <- objectsPositionU13SG5[objectsPositionU13SG5$objPosition %like% "Cube2", ]
Cube2U13SG5$Utente <- "U13SG"
## controllo ultima posizione
U13SG5_check_Cube2 <- tail(Cube2U13SG5, n = 1)

CylinderU13SG5 <- objectsPositionU13SG5[objectsPositionU13SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U13SG5_check_Cylinder <- tail(CylinderU13SG5, n = 1)

CubeU13SG5 <- objectsPositionU13SG5[objectsPositionU13SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U13SG5_check_Cube <- tail(CubeU13SG5, n = 1)

Cylinder2U13SG5 <- objectsPositionU13SG5[objectsPositionU13SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U13SG5_check_Cylinder2 <- tail(Cylinder2U13SG5, n = 1)

SphereU13SG5 <- objectsPositionU13SG5[objectsPositionU13SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U13SG5_check_Sphere <- tail(SphereU13SG5, n = 1)

U13SG5_check_total <- rbind(U13SG5_check_Cube2, U13SG5_check_Cylinder,
                            U13SG5_check_Cube, U13SG5_check_Cylinder2,
                            U13SG5_check_Sphere)
write.xlsx(U13SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U13SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U14SG5 -------------------
## copio dati da JSON
U14SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_08_11_34_00_U14.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU14SG5<-U14SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU14SG5<-U14SG5[[2]][[1]]
objectsPositionU14SG5$Utente <- "U14SG"
write.xlsx(objectsPositionU14SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU14SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U14SG5 <- objectsPositionU14SG5[objectsPositionU14SG5$objPosition %like% "Cube2", ]
Cube2U14SG5$Utente <- "U14SG"
## controllo ultima posizione
U14SG5_check_Cube2 <- tail(Cube2U14SG5, n = 1)

CylinderU14SG5 <- objectsPositionU14SG5[objectsPositionU14SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U14SG5_check_Cylinder <- tail(CylinderU14SG5, n = 1)

CubeU14SG5 <- objectsPositionU14SG5[objectsPositionU14SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U14SG5_check_Cube <- tail(CubeU14SG5, n = 1)

Cylinder2U14SG5 <- objectsPositionU14SG5[objectsPositionU14SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U14SG5_check_Cylinder2 <- tail(Cylinder2U14SG5, n = 1)

SphereU14SG5 <- objectsPositionU14SG5[objectsPositionU14SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U14SG5_check_Sphere <- tail(SphereU14SG5, n = 1)

U14SG5_check_total <- rbind(U14SG5_check_Cube2, U14SG5_check_Cylinder,
                            U14SG5_check_Cube, U14SG5_check_Cylinder2,
                            U14SG5_check_Sphere)
write.xlsx(U14SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U14SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U15SG5 -------------------
## copio dati da JSON
U15SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_08_15_33_07_U15.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU15SG5<-U15SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU15SG5<-U15SG5[[2]][[1]]
objectsPositionU15SG5$Utente <- "U15SG"
write.xlsx(objectsPositionU15SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU15SG5", append=TRUE)

## creo tabella per ogni oggetto
Cube2U15SG5 <- objectsPositionU15SG5[objectsPositionU15SG5$objPosition %like% "Cube2", ]
Cube2U15SG5$Utente <- "U15SG"
## controllo ultima posizione
U15SG5_check_Cube2 <- tail(Cube2U15SG5, n = 1)

CylinderU15SG5 <- objectsPositionU15SG5[objectsPositionU15SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U15SG5_check_Cylinder <- tail(CylinderU15SG5, n = 1)

CubeU15SG5 <- objectsPositionU15SG5[objectsPositionU15SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U15SG5_check_Cube <- tail(CubeU15SG5, n = 1)

Cylinder2U15SG5 <- objectsPositionU15SG5[objectsPositionU15SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U15SG5_check_Cylinder2 <- tail(Cylinder2U15SG5, n = 1)

SphereU15SG5 <- objectsPositionU15SG5[objectsPositionU15SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U15SG5_check_Sphere <- tail(SphereU15SG5, n = 1)

U15SG5_check_total <- rbind(U15SG5_check_Cube2, U15SG5_check_Cylinder,
                            U15SG5_check_Cube, U15SG5_check_Cylinder2,
                            U15SG5_check_Sphere)
write.xlsx(U15SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U15SG5_check_total", append=TRUE)
```

```{r}
## ------------------- U16SG5 -------------------
## copio dati da JSON
U16SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_08_16_18_05_U16.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU16SG5<-U16SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU16SG5<-U16SG5[[2]][[1]]
objectsPositionU16SG5$Utente <- "U16SG"

## creo tabella per ogni oggetto
Cube2U16SG5 <- objectsPositionU16SG5[objectsPositionU16SG5$objPosition %like% "Cube2", ]
Cube2U16SG5$Utente <- "U16SG"
## controllo ultima posizione
U16SG5_check_Cube2 <- tail(Cube2U16SG5, n = 1)

CylinderU16SG5 <- objectsPositionU16SG5[objectsPositionU16SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U16SG5_check_Cylinder <- tail(CylinderU16SG5, n = 1)

CubeU16SG5 <- objectsPositionU16SG5[objectsPositionU16SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U16SG5_check_Cube <- tail(CubeU16SG5, n = 1)

Cylinder2U16SG5 <- objectsPositionU16SG5[objectsPositionU16SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U16SG5_check_Cylinder2 <- tail(Cylinder2U16SG5, n = 1)

SphereU16SG5 <- objectsPositionU16SG5[objectsPositionU16SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U16SG5_check_Sphere <- tail(SphereU16SG5, n = 1)

U16SG5_check_total <- rbind(U16SG5_check_Cube2, U16SG5_check_Cylinder,
                            U16SG5_check_Cube, U16SG5_check_Cylinder2,
                            U16SG5_check_Sphere)

write.xlsx(U16SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U16SG5_check_total", append=TRUE)
write.xlsx(objectsPositionU16SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU16SG5", append=TRUE)
```

```{r}
## ------------------- U17SG5 -------------------
## copio dati da JSON
U17SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_09_09_47_39_U17.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU17SG5<-U17SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU17SG5<-U17SG5[[2]][[1]]
objectsPositionU17SG5$Utente <- "U17SG"

## creo tabella per ogni oggetto
Cube2U17SG5 <- objectsPositionU17SG5[objectsPositionU17SG5$objPosition %like% "Cube2", ]
Cube2U17SG5$Utente <- "U17SG"
## controllo ultima posizione
U17SG5_check_Cube2 <- tail(Cube2U17SG5, n = 1)

CylinderU17SG5 <- objectsPositionU17SG5[objectsPositionU17SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U17SG5_check_Cylinder <- tail(CylinderU17SG5, n = 1)

CubeU17SG5 <- objectsPositionU17SG5[objectsPositionU17SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U17SG5_check_Cube <- tail(CubeU17SG5, n = 1)

Cylinder2U17SG5 <- objectsPositionU17SG5[objectsPositionU17SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U17SG5_check_Cylinder2 <- tail(Cylinder2U17SG5, n = 1)

SphereU17SG5 <- objectsPositionU17SG5[objectsPositionU17SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U17SG5_check_Sphere <- tail(SphereU17SG5, n = 1)

U17SG5_check_total <- rbind(U17SG5_check_Cube2, U17SG5_check_Cylinder,
                            U17SG5_check_Cube, U17SG5_check_Cylinder2,
                            U17SG5_check_Sphere)

write.xlsx(U17SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U17SG5_check_total", append=TRUE)
write.xlsx(objectsPositionU17SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU17SG5", append=TRUE)
```

```{r}
## ------------------- U18SG5 -------------------
## copio dati da JSON
U18SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_09_10_32_55_U18.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU18SG5<-U18SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU18SG5<-U18SG5[[2]][[1]]
objectsPositionU18SG5$Utente <- "U18SG"

## creo tabella per ogni oggetto
Cube2U18SG5 <- objectsPositionU18SG5[objectsPositionU18SG5$objPosition %like% "Cube2", ]
Cube2U18SG5$Utente <- "U18SG"
## controllo ultima posizione
U18SG5_check_Cube2 <- tail(Cube2U18SG5, n = 1)

CylinderU18SG5 <- objectsPositionU18SG5[objectsPositionU18SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U18SG5_check_Cylinder <- tail(CylinderU18SG5, n = 1)

CubeU18SG5 <- objectsPositionU18SG5[objectsPositionU18SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U18SG5_check_Cube <- tail(CubeU18SG5, n = 1)

Cylinder2U18SG5 <- objectsPositionU18SG5[objectsPositionU18SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U18SG5_check_Cylinder2 <- tail(Cylinder2U18SG5, n = 1)

SphereU18SG5 <- objectsPositionU18SG5[objectsPositionU18SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U18SG5_check_Sphere <- tail(SphereU18SG5, n = 1)

U18SG5_check_total <- rbind(U18SG5_check_Cube2, U18SG5_check_Cylinder,
                            U18SG5_check_Cube, U18SG5_check_Cylinder2,
                            U18SG5_check_Sphere)

write.xlsx(U18SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U18SG5_check_total", append=TRUE)
write.xlsx(objectsPositionU18SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU18SG5", append=TRUE)
```

```{r}
## ------------------- U19SG5 -------------------
## copio dati da JSON
U19SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_09_11_59_25_U19.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU19SG5<-U19SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU19SG5<-U19SG5[[2]][[1]]
objectsPositionU19SG5$Utente <- "U19SG"

## creo tabella per ogni oggetto
Cube2U19SG5 <- objectsPositionU19SG5[objectsPositionU19SG5$objPosition %like% "Cube2", ]
Cube2U19SG5$Utente <- "U19SG"
## controllo ultima posizione
U19SG5_check_Cube2 <- tail(Cube2U19SG5, n = 1)

CylinderU19SG5 <- objectsPositionU19SG5[objectsPositionU19SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U19SG5_check_Cylinder <- tail(CylinderU19SG5, n = 1)

CubeU19SG5 <- objectsPositionU19SG5[objectsPositionU19SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U19SG5_check_Cube <- tail(CubeU19SG5, n = 1)

Cylinder2U19SG5 <- objectsPositionU19SG5[objectsPositionU19SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U19SG5_check_Cylinder2 <- tail(Cylinder2U19SG5, n = 1)

SphereU19SG5 <- objectsPositionU19SG5[objectsPositionU19SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U19SG5_check_Sphere <- tail(SphereU19SG5, n = 1)

U19SG5_check_total <- rbind(U19SG5_check_Cube2, U19SG5_check_Cylinder,
                            U19SG5_check_Cube, U19SG5_check_Cylinder2,
                            U19SG5_check_Sphere)

write.xlsx(U19SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U19SG5_check_total", append=TRUE)
write.xlsx(objectsPositionU19SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU19SG5", append=TRUE)
```

```{r}
## ------------------- U20SG5 -------------------
## copio dati da JSON
U20SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_09_14_07_08_U20.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU20SG5<-U20SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU20SG5<-U20SG5[[2]][[1]]
objectsPositionU20SG5$Utente <- "U20SG"

## creo tabella per ogni oggetto
Cube2U20SG5 <- objectsPositionU20SG5[objectsPositionU20SG5$objPosition %like% "Cube2", ]
Cube2U20SG5$Utente <- "U20SG"
## controllo ultima posizione
U20SG5_check_Cube2 <- tail(Cube2U20SG5, n = 1)

CylinderU20SG5 <- objectsPositionU20SG5[objectsPositionU20SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U20SG5_check_Cylinder <- tail(CylinderU20SG5, n = 1)

CubeU20SG5 <- objectsPositionU20SG5[objectsPositionU20SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U20SG5_check_Cube <- tail(CubeU20SG5, n = 1)

Cylinder2U20SG5 <- objectsPositionU20SG5[objectsPositionU20SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U20SG5_check_Cylinder2 <- tail(Cylinder2U20SG5, n = 1)

SphereU20SG5 <- objectsPositionU20SG5[objectsPositionU20SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U20SG5_check_Sphere <- tail(SphereU20SG5, n = 1)

U20SG5_check_total <- rbind(U20SG5_check_Cube2, U20SG5_check_Cylinder,
                            U20SG5_check_Cube, U20SG5_check_Cylinder2,
                            U20SG5_check_Sphere)

write.xlsx(U20SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U20SG5_check_total", append=TRUE)
write.xlsx(objectsPositionU20SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU20SG5", append=TRUE)
```

```{r}
## ------------------- U21SG5 -------------------
## copio dati da JSON
U21SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_09_15_19_56_U21.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU21SG5<-U21SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU21SG5<-U21SG5[[2]][[1]]
objectsPositionU21SG5$Utente <- "U21SG"

## creo tabella per ogni oggetto
Cube2U21SG5 <- objectsPositionU21SG5[objectsPositionU21SG5$objPosition %like% "Cube2", ]
Cube2U21SG5$Utente <- "U21SG"
## controllo ultima posizione
U21SG5_check_Cube2 <- tail(Cube2U21SG5, n = 1)

CylinderU21SG5 <- objectsPositionU21SG5[objectsPositionU21SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U21SG5_check_Cylinder <- tail(CylinderU21SG5, n = 1)

CubeU21SG5 <- objectsPositionU21SG5[objectsPositionU21SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U21SG5_check_Cube <- tail(CubeU21SG5, n = 1)

Cylinder2U21SG5 <- objectsPositionU21SG5[objectsPositionU21SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U21SG5_check_Cylinder2 <- tail(Cylinder2U21SG5, n = 1)

SphereU21SG5 <- objectsPositionU21SG5[objectsPositionU21SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U21SG5_check_Sphere <- tail(SphereU21SG5, n = 1)

U21SG5_check_total <- rbind(U21SG5_check_Cube2, U21SG5_check_Cylinder,
                            U21SG5_check_Cube, U21SG5_check_Cylinder2,
                            U21SG5_check_Sphere)

write.xlsx(U21SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U21SG5_check_total", append=TRUE)
write.xlsx(objectsPositionU21SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU21SG5", append=TRUE)
```

```{r}
## ------------------- U22SG5 -------------------
## copio dati da JSON
U22SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_09_16_14_11_U22.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU22SG5<-U22SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU22SG5<-U22SG5[[2]][[1]]
objectsPositionU22SG5$Utente <- "U22SG"

## creo tabella per ogni oggetto
Cube2U22SG5 <- objectsPositionU22SG5[objectsPositionU22SG5$objPosition %like% "Cube2", ]
Cube2U22SG5$Utente <- "U22SG"
## controllo ultima posizione
U22SG5_check_Cube2 <- tail(Cube2U22SG5, n = 1)

CylinderU22SG5 <- objectsPositionU22SG5[objectsPositionU22SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U22SG5_check_Cylinder <- tail(CylinderU22SG5, n = 1)

CubeU22SG5 <- objectsPositionU22SG5[objectsPositionU22SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U22SG5_check_Cube <- tail(CubeU22SG5, n = 1)

Cylinder2U22SG5 <- objectsPositionU22SG5[objectsPositionU22SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U22SG5_check_Cylinder2 <- tail(Cylinder2U22SG5, n = 1)

SphereU22SG5 <- objectsPositionU22SG5[objectsPositionU22SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U22SG5_check_Sphere <- tail(SphereU22SG5, n = 1)

U22SG5_check_total <- rbind(U22SG5_check_Cube2, U22SG5_check_Cylinder,
                            U22SG5_check_Cube, U22SG5_check_Cylinder2,
                            U22SG5_check_Sphere)

write.xlsx(U22SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U22SG5_check_total", append=TRUE)
write.xlsx(objectsPositionU22SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU22SG5", append=TRUE)
```

```{r}
## ------------------- U23SG5 -------------------
## copio dati da JSON
U23SG5 <- as_tibble(fromJSON("G:/Il mio Drive/Università/20_21_Tesi/JSON/SG/HapticMemorySequenceLog_2021_11_10_09_53_55_U23.json"))

## creo tabella contenente i movimenti della scatola rossa
objInTheBoxU23SG5<-U23SG5[[1]][[1]]

## creo tabella contenente le posizioni iniziali e finali degli oggetti
objectsPositionU23SG5<-U23SG5[[2]][[1]]
objectsPositionU23SG5$Utente <- "U23SG"

## creo tabella per ogni oggetto
Cube2U23SG5 <- objectsPositionU23SG5[objectsPositionU23SG5$objPosition %like% "Cube2", ]
Cube2U23SG5$Utente <- "U23SG"
## controllo ultima posizione
U23SG5_check_Cube2 <- tail(Cube2U23SG5, n = 1)

CylinderU23SG5 <- objectsPositionU23SG5[objectsPositionU23SG5$objPosition %like% "Cylinder", ]
## controllo ultima posizione
U23SG5_check_Cylinder <- tail(CylinderU23SG5, n = 1)

CubeU23SG5 <- objectsPositionU23SG5[objectsPositionU23SG5$objPosition %like% "Cube", ]
## controllo ultima posizione
U23SG5_check_Cube <- tail(CubeU23SG5, n = 1)

Cylinder2U23SG5 <- objectsPositionU23SG5[objectsPositionU23SG5$objPosition %like% "Cylinder2", ]
## controllo ultima posizione
U23SG5_check_Cylinder2 <- tail(Cylinder2U23SG5, n = 1)

SphereU23SG5 <- objectsPositionU23SG5[objectsPositionU23SG5$objPosition %like% "Sphere", ]
## controllo ultima posizione
U23SG5_check_Sphere <- tail(SphereU23SG5, n = 1)

U23SG5_check_total <- rbind(U23SG5_check_Cube2, U23SG5_check_Cylinder,
                            U23SG5_check_Cube, U23SG5_check_Cylinder2,
                            U23SG5_check_Sphere)

write.xlsx(U23SG5_check_total, file = "objectsPositionSG5.xlsx", sheetName="U23SG5_check_total", append=TRUE)
write.xlsx(objectsPositionU23SG5, file = "objectsPositionSG5.xlsx", sheetName="objectsPositionU23SG5", append=TRUE)
```